### ISSUE TITLE
Merge data does not work

### ISSUE THREAD

**Issue by fkeramati** [timoast/signac#347] opened 2020-11-26 21:55 UTC
Hi,

I'm trying to analyze and merge (and then integrate) 3 bone marrow scATAC data. I've done peak calling on the merged dataset in ArchR and now have a unified peak set. I generated three signac objects for each bone marrow sample and ran 
TFIDF and SVD on each. 

```
bm1 = RunTFIDF(bm1)
Warning message:
In RunTFIDF.default(object = GetAssayData(object = object, slot = "counts"),  :
  Some features contain 0 total counts
bm1 = FindTopFeatures(bm1, min.cutoff = "q50")
bm1 = RunSVD(bm1, irlba.work = 400, assay = "peaks")

bm2 = RunTFIDF(bm2)
Warning message:
In RunTFIDF.default(object = GetAssayData(object = object, slot = "counts"),  :
  Some features contain 0 total counts
bm2 = FindTopFeatures(bm2, min.cutoff = "q50")
bm2 = RunSVD(bm2, irlba.work = 400, assay = "peaks")

bm3 = RunTFIDF(bm3)
Warning message:
In RunTFIDF.default(object = GetAssayData(object = object, slot = "counts"),  :
  Some features contain 0 total counts
bm3 = FindTopFeatures(bm3, min.cutoff = "q50")
bm3 = RunSVD(bm3, irlba.work = 400, assay = "peaks")
```

Now each object has 206609 peaks with the same coordinates. When I try to merge them with the following code, nothing happens after even several hours!!!
`unitegrated = merge(bm1, c(bm2, bm3))`

I tried to generate a single fragments.tsv.gz file from the three samples and make a single signac object. This approach works fine. But, then this time when I try to do the Integration, with `IntegrateData` program gives me subscript out of bounds error!! 
I should mention that I have added sample specific prefix to cell names before hand.
What should I do to solve this problem and be able to run cca on my 3 samples? I have a batch effect and need to correct for it.

Thanks
Farid

**Comment by timoast** [comment] 2020-11-26 23:06
Please include the full code you're running

**Comment by fkeramati** [comment] 2020-11-26 23:16
This is the whole code:

`suppressMessages(library(Seurat))
suppressMessages(library(Signac))
suppressMessages(library(ArchR))

projHeme5 = loadArchRProject("SaveProjHeme5/")
peaks = getPeakSet(projHeme5)

bm_frag = CreateFragmentObject(path = "Day0/fragments.tsv.gz", cells = BM1_cells)
bm.counts = FeatureMatrix(fragments = bm_frag, features = peaks, cells = BM1_cells)
bm_assay = CreateChromatinAssay(bm.counts, fragments = bm_frag, min.cells = -1, genome = "hg38")
bm1 = CreateSeuratObject(bm_assay, assay = "peaks")
bm1 = RenameCells(bm1, add.cell.id = "D3105_D0")

bm_frag = CreateFragmentObject(path = "4h/fragments.tsv.gz", cells = BM2_cells)
bm.counts = FeatureMatrix(fragments = bm_frag, features = peaks, cells = BM2_cells)
bm_assay = CreateChromatinAssay(bm.counts, fragments = bm_frag, min.cells = -1, genome = "hg38")
bm2 = CreateSeuratObject(bm_assay, assay = "peaks")
bm2 = RenameCells(bm2, add.cell.id = "D3105_4h")

bm_frag = CreateFragmentObject(path = "Day7/fragments.tsv.gz", cells = BM3_cells)
bm.counts = FeatureMatrix(fragments = bm_frag, features = peaks, cells = BM3_cells)
bm_assay = CreateChromatinAssay(bm.counts, fragments = bm_frag, min.cells = -1, genome = "hg38")
bm3 = CreateSeuratObject(bm_assay, assay = "peaks")
bm3 = RenameCells(bm3, add.cell.id = "D3105_D7")

bm1 = RunTFIDF(bm1)
bm1 = FindTopFeatures(bm1, min.cutoff = "q50")
bm1 = RunSVD(bm1, irlba.work = 400, assay = "peaks")

bm2 = RunTFIDF(bm2)
bm2 = FindTopFeatures(bm2, min.cutoff = "q50")
bm2 = RunSVD(bm2, irlba.work = 400, assay = "peaks")

bm3 = RunTFIDF(bm3)
bm3 = FindTopFeatures(bm3, min.cutoff = "q50")
bm3 = RunSVD(bm3, irlba.work = 400, assay = "peaks")

unintegrated = merge(bm1, c(bm2, bm3))
`

BM1_cells, BM2_cells, BM3_cells are the cell names that passed the quality control steps in ArchR.

Thanks,
Farid

**Comment by timoast** [comment] 2020-11-26 23:31
How many cells are in each dataset? FYI, the `CallPeaks` function in Signac can also be used to call peaks

**Comment by fkeramati** [comment] 2020-11-26 23:36
There are: 3432 cells in bm1, 2823 cells in bm2, 3706 cells in bm3.

```
> bm1
An object of class Seurat 
206609 features across 3432 samples within 1 assay 
Active assay: peaks (206609 features, 104750 variable features)
 2 dimensional reductions calculated: lsi, umap
> bm2
An object of class Seurat 
206609 features across 2823 samples within 1 assay 
Active assay: peaks (206609 features, 104553 variable features)
 2 dimensional reductions calculated: lsi, umap
> bm3
An object of class Seurat 
206609 features across 3706 samples within 1 assay 
Active assay: peaks (206609 features, 104605 variable features)
 2 dimensional reductions calculated: lsi, umap
```

Thanks for `CallPeaks`, will check it out. I was always thinking that peak calling function is missing from Signac.

**Comment by timoast** [comment] 2020-11-26 23:56
Thanks, I'm not sure why this would take so long to merge. If you can send a link to the three objects to tstuart@nygenome.org I'd be happy to take a look and see if I can work out what the issue is

**Comment by fkeramati** [comment] 2020-11-26 23:59
Thanks. I have to check with administrative office if I can share data. These are patient data and we have to comply with strict rules!

**Comment by fkeramati** [comment] 2020-11-27 00:42
Maybe this can hint you to the problem. When I tried to integrate them with cca, I got this error!

```
> anchors <- FindIntegrationAnchors(
  object.list = list(bm1, bm2, bm3),
  anchor.features = rownames(bm1),
  assay = c('peaks', 'peaks', "peaks"), k.filter = NA)

> integrated <- IntegrateData(
  anchorset = anchors,
  weight.reduction = bm1[['lsi']],
  dims = 2:30, preserve.order = TRUE)
```

The error is:
```
Scaling features for provided objects
Finding all pairwise anchors
Running CCA
Merging objects
Error in SetAssayData.ChromatinAssay(object = new.assay, slot = "scale.data",  : 
  Number of rows in provided matrix does not match
           the number of rows in the object
Calls: FindIntegrationAnchors ... merge.ChromatinAssay -> SetAssayData -> SetAssayData.ChromatinAssay
Execution halted
```


What do you think?

**Comment by timoast** [comment] 2020-11-27 01:57
This could be related to an old bug, what version are you using?

**Comment by fkeramati** [comment] 2020-11-27 17:50
I updated Signac to the lates develop version. Now the new error is:

```
Scaling features for provided objects
Finding all pairwise anchors
Running CCA
Merging objects
Warning: No filtering performed if passing to data rather than counts
Error in ecdf(x = featurecounts) : 
  'x' must have 1 or more non-missing values
Calls: FindIntegrationAnchors ... FindTopFeatures.Assay -> FindTopFeatures -> FindTopFeatures.default -> ecdf
Execution halted
```

By the way, merging worked, although it takes more than one hour to merge the three objects.

**Comment by timoast** [comment] 2020-12-03 16:05
This should be fixed on the develop branch

**Comment by fkeramati** [comment] 2020-12-06 12:27
Yes, it worked.
Thanks a lot.

**Closed** 2020-12-06 16:35 UTC
Labels: question
