### ISSUE TITLE
merge function issue

### ISSUE THREAD

**Issue by AnjaliC4** [timoast/signac#402] opened 2021-01-18 02:42 UTC
Hi Tim,

I am using signac 1.1.0 and recently updated to seurat 3.2.3, and what I am trying to do is:
control <- reduce(x = c(control1.peaks,control2.peaks,control3.peaks))
treatment <- reduce(x = c(treatment1.peaks, treatment2.peaks, treatment3.peaks))
peaks <- disjoin(x=c(control, treatment))

Then make the Signac objects following the tutorial with these peaks and merge them. Unfortunately, even after 30mins, merge does not work. It does not give me an error, just does not merge. I am providing 16Gb RAM and 80Gb memory. Infact it did work for me earlier, when I was using the same data but older version of Seurat (can't remember which one). Could there be version compatibility issue or something else that you can think of?
Thanks for your advise!

**Comment by skilpinen** [comment] 2021-01-18 09:25
Hi,

I encountered similar issue. I have two datasets with identical features (binned 5k coordinates) though some are filtered away in both sets. In overall there are about 200 000 features common between datasets with about 2500 and 3000 cells. ChromatinAssay from both, then Seurat object from both and then merge.

It starts to do it but it is so slow that on many days I interrupted it after hours of run. Now I left it for the weekend and today morning it was done (Macbook Pro with fast i7 and 32GB RAM). It took nearly 48h to do it.

However, something is still maybe wrong. Resulting merged object does have only 67607 features. I don't know why or what caused it to drop majority of features.

So there are perhaps two problems. Something odd going on with the speed, and then is there something wrong in merging features or I just don't understand reasoning of dropping features.

**Comment by AnjaliC4** [comment] 2021-01-23 02:13
Hi @timoast would really appreciate your input on this.

**Comment by timoast** [comment] 2021-01-30 00:12
It is definitely weird that it would take so long to merge. I would suggest checking that the features in each object are exactly the same, and removing any additional assays that are not needed. As a workaround, I'd suggest creating a single object containing all the cells rather than creating individual objects and merging them. If you're able to share a couple of objects that reproduce this merging issue, please email me a link at tstuart@nygenome.org and I will be happy to look into it further.

**Comment by timoast** [comment] 2021-02-09 21:03
Merging objects should be significantly improved in the latest version on the develop branch (1.1.1.9001)

**Closed by timoast** 2021-02-09 21:03 UTC
Labels: question

**Comment by vkartha** [comment] 2025-08-15 23:24
Just noting that I have had a run (across 4 objects) that has also been running for > 48 hours (and seems stuck but is still going), it's run faster before but I'm not sure if it's a function of how many peaks each has, or how many cells are in each object (probably both?):

```
|========================================================================================================| 100%
Binding matrix rows
  |========================================================================================================| 100%
Binding matrix rows
  |=========================================================================================================| 100%
```

I'd usually find a consolidated peak set first, then use the same to get counts per sample (since cellranger for instance will have different peak sets per sample by default, which is when I use this merge function at times)
