### ISSUE TITLE
gene.activate showing duplicate gene name in createAssayObject function error

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#54] opened 2019-12-31 02:40 UTC
Hello Tim,
 There are another question generated by create active gene count showing duplicate gene name at 
gene.activities genes count matrix. when i using make.unique function to filter duplicate gene ,it would change gene name into NA. could you help me find this issue out? Thanks.

```r
names(gene.key) <- GRangesToString(grange = genebodyandpromoter.coords)
rownames(gene.activities) <- gene.key[rownames(gene.activities)]
# add the gene activity matrix to the Seurat object as a new assay, and normalize it
testic[['RNA']] <- CreateAssayObject(counts = gene.activities)
```

**Comment by timoast** [comment] 2019-12-31 03:51
Are you sure `make.unique` is the problem, and there are not `NA` values before running `make.unique`?

**Comment by honghh2018** [comment] 2019-12-31 03:58
full code:
gene.key <- genebodyandpromoter.coords$gene_name
names(gene.key) <- GRangesToString(grange = genebodyandpromoter.coords)
rownames(gene.activities) <- gene.key[rownames(gene.activities)]
rownames(gene.activities) <- make.unique(gene.key[rownames(gene.activities)])



The result of activated gene count including NA showing below picture:





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tim Stuart"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 中午11:51
收件人:&nbsp;"timoast/signac"<signac@noreply.github.com&gt;;
抄送:&nbsp;"洪汉辉"<939869915@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [timoast/signac] gene.activate showing duplicate gene name in createAssayObject function error (#54)



Are you sure make.unique is the problem, and there are not NA values before running make.unique?

**Comment by timoast** [comment] 2019-12-31 03:59
You can't attach images though email, please upload it though github

**Comment by honghh2018** [comment] 2019-12-31 04:12
Hi Tim,
    the Na counts of activate count shotscreen showing below:
    
![image](https://user-images.githubusercontent.com/41668708/71609853-cc571700-2bc6-11ea-9c92-bb5ec71787cb.png)

**Comment by honghh2018** [comment] 2019-12-31 04:14
Hi Tim,
    full code:
gene.key <- genebodyandpromoter.coords$gene_name
names(gene.key) <- GRangesToString(grange = genebodyandpromoter.coords)
rownames(gene.activities) <- gene.key[rownames(gene.activities)]
rownames(gene.activities) <- make.unique(gene.key[rownames(gene.activities)])

 The below of using unique.make function processing active genes matrix shotscreen picture:
     
![image](https://user-images.githubusercontent.com/41668708/71609894-09bba480-2bc7-11ea-99cd-6c34853986cf.png)

**Comment by timoast** [comment] 2019-12-31 15:28
It looks like the NA values are present before running `make.unique`. You should look at the objects at each step of the code and work out at what stage you're getting `NA`

**Comment by timoast** [comment] 2020-01-03 16:16
Did you resolve this? If so I'll close the issue

**Comment by honghh2018** [comment] 2020-01-06 02:58
Hi Tim,
     The matirx which was included by ATAC had correctly rowname showing,chr1:198768-198968, but error occured NA when runing  make.unique. I can't find it out what happen on it.please help me to resolve this problem.

**Comment by timoast** [comment] 2020-01-06 03:23
The issue is not with `make.unique`. You need to provide more information if you want this resolved. For example, what are the rownames of `gene.activities` when it is first created and what are the names of `gene.key`?

**Closed** 2020-01-07 15:05 UTC
