### ISSUE TITLE
Footprint function error: unable to find an inherited method for function

### ISSUE THREAD

**Issue by drink-water16** [timoast/signac#960] opened 2022-02-07 22:50 UTC
Hi Tim,

I am having an issue with getting `Footprint` to work with my data. I have followed the vignettes in general to generate my data and was able to do motif analysis and etc. I know want to try out the footprinting.

My data is mouse. I have tried using both mouse and human with `getMatrixSet`

```
pwm <- getMatrixSet(
  x = JASPAR2020,
  opts = list(species = 9606, all_versions = FALSE)
)
combined <- AddMotifs(combined, genome = BSgenome.Mmusculus.UCSC.mm10, pfm = pwm)

combined <- Footprint(
  object = combined,
  motif.name = c("GATA2"),
  genome = BSgenome.Mmusculus.UCSC.mm10
)
```

After running for a while I get the following output

```
Computing Tn5 insertion bias
Extracting reads in requested region
Extracting reads in requested region
Computing observed Tn5 insertions per base
Loading required package: BSgenome
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ, clusterExport, clusterMap, parApply,
    parCapply, parLapply, parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames, dirname, do.call, duplicated, eval,
    evalq, Filter, Find, get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank, rbind, Reduce, rownames, sapply,
    setdiff, sort, table, tapply, union, unique, unsplit, which.max, which.min

Loading required package: S4Vectors
Loading required package: stats4

Attaching package: ‘S4Vectors’

The following objects are masked from ‘package:base’:

    expand.grid, I, unname

Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: GenomicRanges
Loading required package: Biostrings
Loading required package: XVector

Attaching package: ‘Biostrings’

The following object is masked from ‘package:base’:

    strsplit

Loading required package: rtracklayer
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘getSeq’ for signature ‘"BSgenome"’`
```

Any help or suggestions would be great.

**Comment by timoast** [comment] 2022-02-08 19:35
What happens if you run:

```r
library(BSgenome.Mmusculus.UCSC.mm10)
library(Biostrings)
library(GenomicRanges)

gr <- GRanges(seqnames = "chr1", ranges = IRanges(start = 1, end = 100))
getSeq(BSgenome.Mmusculus.UCSC.mm10, gr)
```

**Comment by drink-water16** [comment] 2022-02-08 19:48
```
> gr <- GRanges(seqnames = "chr1", ranges = IRanges(start = 1, end = 100))
> getSeq(BSgenome.Mmusculus.UCSC.mm10, gr)
DNAStringSet object of length 1:
    width seq
[1]   100 NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

**Comment by timoast** [comment] 2022-02-11 21:25
In that case, I'm not sure what the issue is. I'd suggest restarting R (making sure to clear the environment) and try again, and if you still see the error try reinstalling Signac

**Comment by timoast** [comment] 2022-02-28 17:38
Closing this now, please reopen if you're still having issues after trying the suggestions above

**Closed by timoast** 2022-02-28 17:38 UTC

**Comment by neurocycology** [comment] 2022-03-17 13:41
Hello, this is worth re-opening because I am experiencing the exact same issue (followed the same instructions as above). Providing my sessionInfo() since the `Footprint` function was working fine until I recently updated my Bioconductor packages. Happy to provide more info if it will help get to the root of the problem.

R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.10

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
[1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 LC_MONETARY=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8
[7] LC_PAPER=en_US.UTF-8 LC_NAME=C LC_ADDRESS=C LC_TELEPHONE=C LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats4 stats graphics grDevices utils datasets methods base

other attached packages:
[1] future_1.24.0 BSgenome.Hsapiens.UCSC.hg38_1.4.4 BSgenome_1.62.0 rtracklayer_1.54.0
[5] Biostrings_2.62.0 XVector_0.34.0 GenomicRanges_1.46.1 GenomeInfoDb_1.30.1
[9] IRanges_2.28.0 S4Vectors_0.32.3 BiocGenerics_0.40.0 Signac_1.6.0
[13] SeuratObject_4.0.4 Seurat_4.1.0

loaded via a namespace (and not attached):
[1] fastmatch_1.1-3 plyr_1.8.6 igraph_1.2.11 lazyeval_0.2.2 splines_4.1.2
[6] BiocParallel_1.28.3 listenv_0.8.0 scattermore_0.8 SnowballC_0.7.0 ggplot2_3.3.5
[11] digest_0.6.29 htmltools_0.5.2 fansi_1.0.2 magrittr_2.0.2 tensor_1.5
[16] cluster_2.1.2 ROCR_1.0-11 globals_0.14.0 matrixStats_0.61.0 docopt_0.7.1
[21] spatstat.sparse_2.1-0 colorspace_2.0-3 ggrepel_0.9.1 dplyr_1.0.8 sparsesvd_0.2
[26] crayon_1.5.0 RCurl_1.98-1.6 jsonlite_1.8.0 spatstat.data_2.1-2 survival_3.3-1
[31] zoo_1.8-9 glue_1.6.2 polyclip_1.10-0 gtable_0.3.0 zlibbioc_1.40.0
[36] leiden_0.3.9 DelayedArray_0.20.0 future.apply_1.8.1 abind_1.4-5 scales_1.1.1
[41] pheatmap_1.0.12 DBI_1.1.2 spatstat.random_2.1-0 miniUI_0.1.1.1 Rcpp_1.0.8.2
[46] viridisLite_0.4.0 xtable_1.8-4 reticulate_1.24 spatstat.core_2.4-0 htmlwidgets_1.5.4
[51] httr_1.4.2 RColorBrewer_1.1-2 ellipsis_0.3.2 ica_1.0-2 pkgconfig_2.0.3
[56] XML_3.99-0.9 farver_2.1.0 ggseqlogo_0.1 uwot_0.1.11 deldir_1.0-6
[61] utf8_1.2.2 tidyselect_1.1.2 rlang_1.0.2 reshape2_1.4.4 later_1.3.0
[66] munsell_0.5.0 tools_4.1.2 cli_3.2.0 generics_0.1.2 ggridges_0.5.3
[71] stringr_1.4.0 fastmap_1.1.0 yaml_2.3.5 goftest_1.2-3 fitdistrplus_1.1-8
[76] purrr_0.3.4 RANN_2.6.1 pbapply_1.5-0 nlme_3.1-155 mime_0.12
[81] slam_0.1-50 RcppRoll_0.3.0 compiler_4.1.2 rstudioapi_0.13 plotly_4.10.0
[86] png_0.1-7 spatstat.utils_2.3-0 tibble_3.1.6 tweenr_1.0.2 stringi_1.7.6
[91] lattice_0.20-45 Matrix_1.4-0 vctrs_0.3.8 pillar_1.7.0 lifecycle_1.0.1
[96] BiocManager_1.30.16 spatstat.geom_2.3-2 lmtest_0.9-39 RcppAnnoy_0.0.19 data.table_1.14.2
[101] cowplot_1.1.1 bitops_1.0-7 irlba_2.3.5 httpuv_1.6.5 patchwork_1.1.1
[106] BiocIO_1.4.0 R6_2.5.1 promises_1.2.0.1 KernSmooth_2.23-20 gridExtra_2.3
[111] lsa_0.73.2 parallelly_1.30.0 codetools_0.2-18 MASS_7.3-55 assertthat_0.2.1
[116] SummarizedExperiment_1.24.0 rjson_0.2.21 GenomicAlignments_1.30.0 qlcMatrix_0.9.7 sctransform_0.3.3
[121] Rsamtools_2.10.0 GenomeInfoDbData_1.2.7 mgcv_1.8-39 parallel_4.1.2 grid_4.1.2
[126] rpart_4.1.16 tidyr_1.2.0 MatrixGenerics_1.6.0 Rtsne_0.15 ggforce_0.3.3
[131] Biobase_2.54.0 shiny_1.7.1 restfulr_0.0.13

**Comment by neurocycology** [comment] 2022-03-17 21:42
Not sure why this is suddenly acting up, but tried turning off parallelization with future and just running on a single thread. Seemed to solve it, but will report back on this once I test again.

**Comment by neurocycology** [comment] 2022-03-18 02:17
@drink-water16 @timoast can confirm that using a future plan causes this error to occur. running without parallelization solves at least solves the problem in the short term.
