### ISSUE TITLE
Data link discrepancy in PBMC vignette

### ISSUE THREAD

**Issue by joshpeters** [timoast/signac#2] opened 2019-07-17 21:53 UTC
Hey Tim – excited to begin using the package! Thanks for releasing this.

I downloaded the data directly from the vignette, but there was some issues in processing, first encountered in the QC plotting and during filtering (only < 100 samples left using your filters). Downloading the data directly from the 10X website and there was no issues.
The data links are just off a bit? Not sure what the underlying differences are. 

Links from [Signac](https://satijalab.org/signac/articles/pbmc_vignette.html) 
http://cf.10xgenomics.com/samples/cell-atac/1.1.0/atac_v1_pbmc_10k/atac_v1_pbmc_10k_filtered_peak_bc_matrix.h5
http://cf.10xgenomics.com/samples/cell-atac/1.1.0/atac_v1_pbmc_10k/atac_v1_pbmc_10k_fragments.tsv.gz
http://cf.10xgenomics.com/samples/cell-atac/1.1.0/atac_v1_pbmc_10k/atac_v1_pbmc_10k_fragments.tsv.gz.tbi
http://cf.10xgenomics.com/samples/cell-atac/1.1.0/atac_pbmc_10k_v1/atac_pbmc_10k_v1_singlecell.csv

Links for [10X](https://support.10xgenomics.com/single-cell-atac/datasets/1.1.0/atac_pbmc_10k_v1)
http://cf.10xgenomics.com/samples/cell-atac/1.1.0/atac_pbmc_10k_v1/atac_pbmc_10k_v1_filtered_peak_bc_matrix.h5
http://cf.10xgenomics.com/samples/cell-atac/1.1.0/atac_pbmc_10k_v1/atac_pbmc_10k_v1_singlecell.csv
http://cf.10xgenomics.com/samples/cell-atac/1.1.0/atac_pbmc_10k_v1/atac_pbmc_10k_v1_fragments.tsv.gz.tbi
http://cf.10xgenomics.com/samples/cell-atac/1.1.0/atac_pbmc_10k_v1/atac_pbmc_10k_v1_fragments.tsv.gz

**Comment by timoast** [comment] 2019-07-17 22:29
Hi Josh, thanks for pointing this out. The link to the cell metadata in the Signac PBMC vignette is wrong and I will fix it soon. The correct link for the PBMC cell metadata for the count matrix we use in the vignette is http://cf.10xgenomics.com/samples/cell-atac/1.1.0/atac_v1_pbmc_10k/atac_v1_pbmc_10k_singlecell.csv

10x has, confusingly, different PBMC datasets named atac_v1_pbmc_10k and atac_pbmc_10k_v1 (we used atac_v1_pbmc_10k).

This should be the cause of the problem, but please let me know if you still have issues when using the other metadata

**Comment by timoast** [comment] 2019-07-17 22:47
Link should be fixed on the website now

**Closed by timoast** 2019-07-17 22:47 UTC

**Comment by centrabiohub** [comment] 2022-10-21 11:56
In medical research, **_[peripheral blood mononuclear cells](https://centralbiohub.de/biospecimens/cell-products/pbmc)_** (PBMC) are an incredible tool for molecular and immunological studies. As we know, lymphocytes, monocytes, and macrophages are specialized white blood cells that play an important role in human immunity. PBMC study helps in discovering new possibilities in precision medicine research and individualized therapy due to their great accuracy and sensitivity in terms of genetic diversity and chemical exposure. **_[Central BioHub](https://centralbiohub.de)_** provides exceptional quality PBMC samples lawfully acquired from various people to fuel rational medical research. Explore our inventory order samples online!
