### ISSUE TITLE
Still no nucleosome_signal on Vlnplot

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#93] opened 2020-02-16 07:46 UTC
Hi @timoast  
     The data for my project using your workflow to preprocess still abnormal on Vlnplot.
     The code showing below:
F1<-Read10X_h5('/share/nas1/Data/Users/honghh/ScRNA_Project/jida_project_data/39/F1/outs/filtered_peak_bc_matrix.h5')

f1metadata <- read.csv(
  file = "/share/nas1/Data/Users/honghh/ScRNA_Project/jida_project_data/39/F1/outs/singlecell.csv",
  header = TRUE,
  row.names = 1
)
f1 <- CreateSeuratObject(
  counts = F1,
  assay = 'peaks',
  project = 'F1',
  min.cells = 1,
  meta.data = f1metadata
)
    f1fragment.path <- '/share/nas1/Data/Users/honghh/ScRNA_Project/jida_project_data/39/F1/outs/fragments.tsv.gz'

f1 <- SetFragments(
  object = f1,
  file = f1fragment.path
)
f1 <- NucleosomeSignal(object = f1)
f1$pct_reads_in_peaks <- f1$peak_region_fragments / f1$passed_filters * 100
f1$blacklist_ratio <- f1$blacklist_region_fragments / f1$peak_region_fragments

VlnPlot(
  object = f1,
  features = c('pct_reads_in_peaks', 'blacklist_ratio', 'nucleosome_signal', 'peak_region_fragments'),
  pt.size = 0.1,
  ncol = 4) + NoLegend()
View(f1@meta.data)

     The picture showing below:
![image](https://user-images.githubusercontent.com/41668708/74600926-ff039300-50d2-11ea-9ca6-c5393fcd50f1.png)
The metadata showing belowing:
![image](https://user-images.githubusercontent.com/41668708/74600950-4ab63c80-50d3-11ea-93f3-3b7d411525d9.png)

![image](https://user-images.githubusercontent.com/41668708/74600938-28242380-50d3-11ea-932f-1d9257afd291.png)
#####the R session info:
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C               LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8    LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
 [1] grid      stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Signac_0.2.0                gdtools_0.2.1               org.Mm.eg.db_3.10.0         clusterProfiler_3.14.2     
 [5] GSVAdata_1.22.0             hgu95a.db_3.2.3             org.Hs.eg.db_3.10.0         GSEABase_1.48.0            
 [9] graph_1.64.0                annotate_1.64.0             XML_3.98-1.20               AnnotationDbi_1.48.0       
[13] GSVA_1.34.0                 Cairo_1.5-10                ggplot2_3.2.1               shiny_1.4.0                
[17] data.table_1.12.8           Seurat_3.1.2                cicero_1.3.4.5              Gviz_1.28.3                
[21] monocle3_0.2.0              SingleCellExperiment_1.8.0  SummarizedExperiment_1.16.1 DelayedArray_0.12.1        
[25] BiocParallel_1.20.1         matrixStats_0.55.0          GenomicRanges_1.38.0        GenomeInfoDb_1.22.0        
[29] IRanges_2.20.1              S4Vectors_0.24.1            Biobase_2.46.0              BiocGenerics_0.32.0        

loaded via a namespace (and not attached):
  [1] rappdirs_0.3.1           rtracklayer_1.46.0       R.methodsS3_1.7.1        tidyr_1.0.0             
  [5] acepack_1.4.1            bit64_0.9-7              knitr_1.26               irlba_2.3.3             
  [9] multcomp_1.4-11          R.utils_2.9.2            rpart_4.1-15             RCurl_1.95-4.12         
 [13] AnnotationFilter_1.10.0  metap_1.2                GenomicFeatures_1.38.1   cowplot_1.0.0           
 [17] TH.data_1.0-10           RSQLite_2.1.5            RANN_2.6.1               europepmc_0.3           
 [21] VGAM_1.1-2               future_1.15.1            ggfittext_0.8.1          bit_1.1-14              
 [25] enrichplot_1.6.1         mutoss_0.1-12            xml2_1.2.2               httpuv_1.5.2            
 [29] assertthat_0.2.1         viridis_0.5.1            xfun_0.11                hms_0.5.2               
 [33] promises_1.1.0           fansi_0.4.0              progress_1.2.2           caTools_1.17.1.3        
 [37] dbplyr_1.4.2             geneplotter_1.64.0       igraph_1.2.4.2           DBI_1.1.0               
 [41] htmlwidgets_1.5.1        ellipsis_0.3.0           purrr_0.3.3              RSpectra_0.16-0         
 [45] gggenes_0.4.0            dplyr_0.8.3              backports_1.1.5          gbRd_0.4-11             
 [49] RcppParallel_4.4.4       biomaRt_2.42.0           vctrs_0.2.1              ensembldb_2.10.2        
 [53] ROCR_1.0-7               withr_2.1.2              ggforce_0.3.1            triebeard_0.3.0         
 [57] BSgenome_1.54.0          checkmate_1.9.4          sctransform_0.2.1        GenomicAlignments_1.22.1
 [61] prettyunits_1.0.2        mnormt_1.5-5             cluster_2.1.0            DOSE_3.12.0             
 [65] ape_5.3                  lazyeval_0.2.2           crayon_1.3.4             hdf5r_1.3.0             
 [69] labeling_0.3             pkgconfig_2.0.3          tweenr_1.0.1             nlme_3.1-143            
 [73] ProtGenerics_1.18.0      nnet_7.3-12              rlang_0.4.2              globals_0.12.5          
 [77] lifecycle_0.1.0          sandwich_2.5-1           BiocFileCache_1.10.2     rsvd_1.0.2              
 [81] dichromat_2.0-0          polyclip_1.10-0          lmtest_0.9-37            ggseqlogo_0.1           
 [85] Matrix_1.2-18            urltools_1.7.3           zoo_1.8-6                base64enc_0.1-3         
 [89] ggridges_0.5.1           png_0.1-7                viridisLite_0.3.0        bitops_1.0-6            
 [93] R.oo_1.23.0              KernSmooth_2.23-16       Biostrings_2.54.0        blob_1.2.0              
 [97] stringr_1.4.0            qvalue_2.18.0            jpeg_0.1-8.1             gridGraphics_0.4-1      
[101] scales_1.1.0             memoise_1.1.0            magrittr_1.5             plyr_1.8.5              
[105] ica_1.0-2                gplots_3.0.1.1           bibtex_0.4.2.1           gdata_2.18.0            
[109] zlibbioc_1.32.0          compiler_3.6.0           lsei_1.2-0               RColorBrewer_1.1-2      
[113] plotrix_3.7-7            fitdistrplus_1.0-14      Rsamtools_2.2.2          cli_2.0.0               
[117] XVector_0.26.0           listenv_0.8.0            patchwork_1.0.0          pbapply_1.4-2           
[121] htmlTable_1.13.3         Formula_1.2-3            MASS_7.3-51.5            tidyselect_0.2.5        
[125] stringi_1.4.3            yaml_2.2.0               GOSemSim_2.12.0          askpass_1.1             
[129] latticeExtra_0.6-29      ggrepel_0.8.1            VariantAnnotation_1.32.0 fastmatch_1.1-0         
[133] tools_3.6.0              future.apply_1.3.0       rstudioapi_0.10          foreign_0.8-74          
[137] gridExtra_2.3            farver_2.0.1             Rtsne_0.15               ggraph_2.0.0            
[141] digest_0.6.23            rvcheck_0.1.7            BiocManager_1.30.10      Rcpp_1.0.3              
[145] SDMTools_1.1-221.2       later_1.0.0              RcppAnnoy_0.0.14         httr_1.4.1              
[149] biovizBase_1.34.1        npsurv_0.4-0             Rdpack_0.11-1            colorspace_1.4-1        
[153] reticulate_1.14          splines_3.6.0            uwot_0.1.5               sn_1.5-4                
[157] graphlayouts_0.5.0       multtest_2.42.0          shinythemes_1.1.2        ggplotify_0.0.4         
[161] systemfonts_0.1.1        plotly_4.9.1             xtable_1.8-4             jsonlite_1.6            
[165] tidygraph_1.1.2          zeallot_0.1.0            R6_2.4.1                 TFisher_0.2.0           
[169] Hmisc_4.3-0              mime_0.8                 pillar_1.4.3             htmltools_0.4.0         
[173] fastmap_1.0.1            glue_1.3.1               codetools_0.2-16         fgsea_1.12.0            
[177] tsne_0.1-3               mvtnorm_1.0-11           lattice_0.20-38          tibble_2.1.3            
[181] numDeriv_2016.8-1.1      curl_4.3                 leiden_0.3.1             gtools_3.8.1            
[185] GO.db_3.10.0             openssl_1.4.1            survival_3.1-8           munsell_0.5.0           
[189] DO.db_2.9                GenomeInfoDbData_1.2.2   reshape2_1.4.3           gtable_0.3.0

**Comment by timoast** [comment] 2020-02-16 15:44
Can you share a reproducible example?

**Comment by honghh2018** [comment] 2020-02-17 08:07
hi @timoast 
Sent the data i analyzed to you ?

**Comment by timoast** [comment] 2020-02-17 22:08
Yes, I haven't been able to reproduce this issue so please share example code and data that reproduces the issue. You can email a link to a downsampled dataset that reproduces the issue to tstuart@nygenome.org

**Comment by honghh2018** [comment] 2020-02-18 04:50
hi @timoast ,
     The data produced error that i analyzed have sent to you by e-meil,tstuart@nygenome.org.

**Comment by timoast** [comment] 2020-02-18 14:02
You sent the count matrix and the cellranger metadata file, that's not sufficient to reproduce this issue. 

Please save the Seurat object that contains the `nucleosome_signal` column using `saveRDS(object, "obj.rds")`, and send that.

**Comment by honghh2018** [comment] 2020-02-21 07:43
Hi @timoast
  The seurat obj has sent you by email. 
   Please check the email on your convenient

**Comment by timoast** [comment] 2020-02-21 22:37
@honghh2018 this was due to the presence of `Inf` values in the `nucleosome_signal`. This would cause the max value for the y-axis to be set to infinity, so it would appear that nothing was in the plot. I have now fixed this in Seurat and the fix will be available in the Seurat develop branch soon. In the mean time, you can get around this by setting the y-axis limit yourself using the `y.max` parameter in `VlnPlot`

**Comment by ahmedabbas81** [comment] 2020-02-24 21:13
Dear all,
I also have the same problem with some datasets. It gives me those warnings:

"Removed 1 rows containing non-finite values (stat_ydensity)."Warning message:
"Removed 270 rows containing non-finite values (stat_bin)."Warning message:
"Removed 4 rows containing missing values (geom_bar)."

I think the first two warnings are due to non-finite values as mentioned in the last comment.

What about the third warning?

Also, does this affect any of the analysis carried on the dataest?

Thank you

**Comment by timoast** [comment] 2020-02-24 21:45
@ahmedabbas81 the last warning is for missing data (probably `NA`s). This is not likely to affect anything

**Comment by timoast** [comment] 2020-03-02 20:19
This is now fixed on the current develop branch of Seurat

**Closed by timoast** 2020-03-02 20:19 UTC
