### ISSUE TITLE
Error in CreateChromatinAssay: Number of ranges provided is not equal to the number of features in the assay

### ISSUE THREAD

**Issue by mlin2017** [timoast/signac#390] opened 2021-01-11 05:54 UTC
Dear Dr. Stuart,

Thank you for developing this amazing tool!

I'm analyzing a scATAC-seq dataset following this tutorial: https://satijalab.org/signac/articles/pbmc_vignette.html

An error occurred from CreateChromatinAssay: 
chrom_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  genome = 'hg19',
  fragments = 'Myfragments.tsv.gz',
  min.cells = 10,
  min.features = 200
)

Computing hash
Checking for 7840 cell barcodes
Error in SetAssayData.ChromatinAssay(object = new.assay, slot = "ranges",  :
  Number of ranges provided is not equal to the number
           of features in the assay

Since I did not provide "ranges", genomic ranges should be extracted from the row names of matrix and the number of ranges should be equal to the number of features. ("A set of genomic ranges must be supplied along with the matrix, with the length of the ranges equal to the number of rows in the matrix. If a set of genomic ranges are not supplied, they will be extracted from the row names of the matrix."). 

Could you please explain a little bit why this error occurred? Any suggestions?

Thanks,
Mao

**Comment by timoast** [comment] 2021-01-13 03:29
What version are you using? Can you provide the output of `sessionInfo()`?

**Comment by mlin2017** [comment] 2021-01-13 03:49
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.5 (Santiago)
  
Matrix products: default
BLAS/LAPACK: MYLIBPATH/libopenblasp-r0.3.12.so
  
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
  
attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets
[8] methods   base
  
other attached packages:
 [1] hdf5r_1.3.3               patchwork_1.1.1
 [3] ggplot2_3.3.3             EnsDb.Hsapiens.v75_2.99.0
 [5] ensembldb_2.14.0          AnnotationFilter_1.14.0
 [7] GenomicFeatures_1.42.1    AnnotationDbi_1.52.0
 [9] Biobase_2.50.0            GenomicRanges_1.42.0
[11] GenomeInfoDb_1.26.2       IRanges_2.24.1
[13] S4Vectors_0.28.1          BiocGenerics_0.36.0
[15] Seurat_3.2.3              Signac_1.1.0

loaded via a namespace (and not attached):
  [1] reticulate_1.18             tidyselect_1.1.0
  [3] RSQLite_2.2.2               htmlwidgets_1.5.3
  [5] grid_4.0.3                  BiocParallel_1.24.1
  [7] Rtsne_0.15                  munsell_0.5.0
  [9] codetools_0.2-18            ica_1.0-2
.....
[157] dplyr_1.0.2                 irlba_2.3.3
[159] future.apply_1.7.0

Let me know if you need any other information. Thanks!

**Comment by timoast** [comment] 2021-01-15 17:51
Can you provide the output of `head(rownames(counts))`?

**Comment by mlin2017** [comment] 2021-01-15 17:58
> head(rownames(counts))
[1] "chr1:10297-10730"   "chr1:237572-237922" "chr1:565087-565564"
[4] "chr1:569162-569655" "chr1:713583-715595" "chr1:752376-754413"

Thanks!

**Comment by joeytai2010** [comment] 2021-01-21 06:46
I found similar issue. Any suggestion? Thanks.

**Comment by skilpinen** [comment] 2021-01-21 08:46
I am encountered the same issue. It appears if there is something set in min.features arguments. Without that it goes through for me.

**Comment by KevinMLanderos** [comment] 2021-01-22 18:52
I found a similar issue, this error appears no matter if I remove min.features, min.cells or both arguments. Hope you can help us!

**Comment by timoast** [comment] 2021-01-30 00:15
Do you still get this error with the current version on the develop branch? If so, would you mind sending me the counts matrix so that I can try to reproduce and fix the error? You can email a download link to tstuart@nygenome.org

**Comment by mlin2017** [comment] 2021-01-30 21:48
This step seems to be ok by removing min.cells and min.features; hopefully this will not affect downstream analyses..

However, new errors came up shortly:

(1)
seqlevelsStyle(annotations) <- 'UCSC'
#Error in file(file, "rt") : 
#  cannot open the connection to 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.25_GRCh37.p13/GCF_000001405.25_GRCh37.p13_assembly_report.txt'
#In addition: Warning message:
#In file(file, "rt") :
#  URL 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.25_GRCh37.p13/GCF_000001405.25_GRCh37.p13_assembly_report.txt': Timeout of 60 seconds was reached

(2) 
# compute TSS enrichment score per cell
pbmc <- TSSEnrichment(object = pbmc, fast = FALSE)
#Extracting TSS positions
#Error in eval(bysub, x, parent.frame()) : object 'gene_name' not found
# add blacklist ratio and fraction of reads in peaks

Error #2 might be caused by Error #1. 

Error # 1 might be caused by  **settings of the cluster** where the job is running, so I installed all those packages on my **own computer and tried to run it locally.** Unfortunately, new error occurred:

> chrom_assay <- CreateChromatinAssay(
+   counts = counts,
+   sep = c(":", "-"),
+   genome = 'hg19',
+   fragments = 'fragments.tsv.gz',
+   min.cells = 10
+   #min.features = 200
+ )
Computing hash
Checking for 9697 cell barcodes
Error in validObject(.Object) : 
  invalid class "ChromatinAssay" object: undefined class for slot "assay.orig" ("OptionalCharacter")

Any suggestions?

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] hdf5r_1.3.3               patchwork_1.1.1           ggplot2_3.3.3             EnsDb.Hsapiens.v75_2.99.0 ensembldb_2.12.1          AnnotationFilter_1.12.0   GenomicFeatures_1.40.1   
 [8] AnnotationDbi_1.50.3      Biobase_2.48.0            GenomicRanges_1.40.0      GenomeInfoDb_1.24.2       IRanges_2.22.2            S4Vectors_0.26.1          BiocGenerics_0.34.0      
[15] SeuratObject_4.0.0        Seurat_4.0.0              Signac_1.1.0      
.....

 > head(rownames(counts))
[1] "chr1:10297-10730"   "chr1:237572-237922" "chr1:565087-565564" "chr1:569162-569655" "chr1:713583-715595" "chr1:752376-754413"     


Thanks.

**Comment by mlin2017** [comment] 2021-01-30 22:14
When I tried with the example data the tutorial used (https://satijalab.org/signac/articles/pbmc_vignette.html), a different error came up:

> seqlevelsStyle(annotations) <- 'UCSC'  
Error in function (type, msg, asError = TRUE)  :
  Failed to connect to ftp.ncbi.nlm.nih.gov port 21: Connection timed out

Is there any solution or workaround to make it work on cluster?

**Comment by timoast** [comment] 2021-01-30 23:31
@mlin2017 looks like your machine can't connect to the internet, or at least not to the ncbi site

**Comment by skilpinen** [comment] 2021-02-01 09:55
Hi,

I’ll test this asap., likely around Wednesday or so. I went around the problem with additional code, but gladly test if I could use only Signac.

Br,
Sami




On 30. Jan 2021, at 2.15, Tim Stuart <notifications@github.com<mailto:notifications@github.com>> wrote:



Do you still get this error with the current version on the develop branch? If so, would you mind sending me the counts matrix so that I can try to reproduce and fix the error? You can email a download link to tstuart@nygenome.org<mailto:tstuart@nygenome.org>

**Comment by timoast** [comment] 2021-02-01 19:23
This should be fixed now on the develop branch. See the website for installation instructions

**Closed by timoast** 2021-02-01 19:23 UTC
Labels: bug
