### ISSUE TITLE
GenomeBin Matrix

### ISSUE THREAD

**Issue by AnjaliC4** [timoast/signac#649] opened 2021-06-04 15:37 UTC
GenomeBinMatrix function with a vector of cell names throws this error:

```r
atac.bins <- GenomeBinMatrix(
fragments = frags,
genome = genome,
cells = rownames(cells),
binsize = 1000,
process_n = 2000
)
head(rownames(cells)) (which I pass to fragment object and GenomeBin matrix)
([1] "ACCTCCAACAGCCTAT" "CAGAAACCTAAATCGA" "TCCGAGTCTGGATGGT" "TGTACGATGAGTCGGA"
[5] "AAGAATGTGATCCTCC" "TCGCGTACTATACGCT"

..
Extracting reads overlapping genomic regions
Error in (function (cl, name, valueClass)  :
  assignment of an object of class "numeric" is not valid for @'Dim' in an object of class "dgTMatrix"; 
 is(value, "integer") is not TRUE
Calls: GenomeBinMatrix ... resolve.list -> signalConditionsASAP -> signalConditions
Execution halted

sessioninfo()
multiprocess:
- args: function (..., envir = parent.frame(), workers = 5)
- tweaked: TRUE
- call: plan("multiprocess", workers = 5)
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/imkl/2018.3.>

locale:
 [1] LC_CTYPE=en_US.UTF-8	LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8	LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] Matrix_1.2-18                     harmony_1.0
 [3] Rcpp_1.0.5                        patchwork_1.1.1
 [5] ggplot2_3.3.3                     BSgenome.Hsapiens.UCSC.hg38_1.4.1
 [7] BSgenome_1.54.0                   rtracklayer_1.46.0
 [9] Biostrings_2.54.0                 XVector_0.26.0
[11] EnsDb.Hsapiens.v86_2.99.0         ensembldb_2.10.2
[13] AnnotationFilter_1.10.0           GenomicFeatures_1.38.2
[15] AnnotationDbi_1.48.0              Biobase_2.46.0
[17] future_1.21.0                     GenomicRanges_1.38.0
[19] GenomeInfoDb_1.22.1               IRanges_2.20.2
[21] S4Vectors_0.24.4                  BiocGenerics_0.32.0
[23] Seurat_3.2.1                      Signac_1.1.0

loaded via a namespace (and not attached):
  [1] reticulate_1.18             tidyselect_1.1.0
  [3] RSQLite_2.2.0               htmlwidgets_1.5.3
  [5] grid_3.6.1                  BiocParallel_1.20.1
  [7] Rtsne_0.15                  munsell_0.5.0
  [9] codetools_0.2-16            ica_1.0-2
 [11] miniUI_0.1.1.1              withr_2.3.0
 [13] colorspace_2.0-0            OrganismDbi_1.28.0
 [15] knitr_1.29                  rstudioapi_0.13
 [17] ROCR_1.0-11                 tensor_1.5
 [19] listenv_0.8.0               GenomeInfoDbData_1.2.2
 [21] polyclip_1.10-0             bit64_0.9-7
 [23] farver_2.0.3                parallelly_1.23.0
 [25] vctrs_0.3.6                 generics_0.1.0
 [27] xfun_0.15                   biovizBase_1.34.1
 [29] BiocFileCache_1.10.2        lsa_0.73.2
 [31] ggseqlogo_0.1               R6_2.5.0
 [33] rsvd_1.0.3                  bitops_1.0-6
 [35] spatstat.utils_1.20-2	  reshape_0.8.8
 [37] DelayedArray_0.12.3         assertthat_0.2.1
[39] promises_1.1.1              scales_1.1.1
 [41] nnet_7.3-12                 gtable_0.3.0
 [43] globals_0.14.0              goftest_1.2-2
 [45] ggbio_1.34.0                rlang_0.4.10
 [47] RcppRoll_0.3.0              splines_3.6.1
 [49] lazyeval_0.2.2              acepack_1.4.1
 [51] dichromat_2.0-0             checkmate_2.0.0
 [53] BiocManager_1.30.10         reshape2_1.4.4
 [55] abind_1.4-5                 backports_1.1.8
 [57] httpuv_1.5.4                Hmisc_4.4-0
 [59] RBGL_1.62.1                 tools_3.6.1
 [61] ellipsis_0.3.1              RColorBrewer_1.1-2
 [63] ggridges_0.5.3              plyr_1.8.6
 [65] base64enc_0.1-3             progress_1.2.2
 [67] zlibbioc_1.32.0             purrr_0.3.4
 [69] RCurl_1.98-1.2              prettyunits_1.1.1
 [71] rpart_4.1-15                openssl_1.4.3
 [73] deldir_0.2-3                pbapply_1.4-3
 [75] cowplot_1.1.1               zoo_1.8-8
[77] SummarizedExperiment_1.16.1 ggrepel_0.9.0
 [79] cluster_2.1.0               magrittr_2.0.1
 [81] data.table_1.13.6           lmtest_0.9-38
 [83] RANN_2.6.1                  SnowballC_0.7.0
 [85] ProtGenerics_1.18.0         fitdistrplus_1.1-3
 [87] matrixStats_0.57.0          hms_0.5.3
 [89] mime_0.9                    xtable_1.8-4
 [91] XML_3.99-0.3                jpeg_0.1-8.1
 [93] gridExtra_2.3               compiler_3.6.1
 [95] biomaRt_2.42.1              tibble_3.0.4
 [97] KernSmooth_2.23-15          crayon_1.3.4
 [99] htmltools_0.5.1.1           mgcv_1.8-28
[101] later_1.1.0.1               Formula_1.2-3
[103] tidyr_1.1.2                 DBI_1.1.0
[105] tweenr_1.0.1                dbplyr_1.4.4
[107] MASS_7.3-51.4               rappdirs_0.3.1
[109] igraph_1.2.6                pkgconfig_2.0.3
[111] GenomicAlignments_1.22.1    foreign_0.8-71
[113] plotly_4.9.3                stringr_1.4.0
[115] VariantAnnotation_1.32.0    digest_0.6.27
[117] sctransform_0.3.2           RcppAnnoy_0.0.18
[119] graph_1.64.0                spatstat.data_1.7-0
[121] leiden_0.3.6                fastmatch_1.1-0
[123] htmlTable_2.0.1             uwot_0.1.10
[125] curl_4.3                    shiny_1.5.0
[127] Rsamtools_2.2.3             lifecycle_0.2.0
[129] nlme_3.1-140                jsonlite_1.7.2
[131] viridisLite_0.3.0           askpass_1.1
[133] pillar_1.4.7                lattice_0.20-38
[135] GGally_2.0.0                fastmap_1.0.1
[137] httr_1.4.2                  survival_3.2-3
[139] glue_1.4.2                  spatstat_1.64-1
[141] png_0.1-7                   bit_1.1-15.2
[143] ggforce_0.3.2               stringi_1.5.3
[145] blob_1.2.1                  latticeExtra_0.6-29
[147] memoise_1.1.0               dplyr_1.0.2
[149] irlba_2.3.3                 future.apply_1.7.0







```

**Comment by timoast** [comment] 2021-06-04 16:26
Can you test this without parallelization (set `plan("sequential")`), and also try with the latest Signac version (1.2.1)?

**Comment by AnjaliC4** [comment] 2021-06-04 21:29
I did what you suggested, I don't get an error anymore, however, it still doesn't take cells into account and creates a count matrix for all the cells in the fragment file.

plan("sequential")
plan()
atac.bins <- GenomeBinMatrix(
fragments = frags,
genome = genome,
cells = rownames(cells),
binsize = 1000,
process_n = 2000
)
print(head(atac6310.bins))
print(dim(atac6310.bins))
print(sessionInfo())

Checking for 6309 cell barcodes
Extracting reads overlapping genomic regions
   [[ suppressing 34 column names 'ACCTCCAACAGCCTAT', 'AGAGTACCTCCTGTGG', 'CAGAAACCTAAATCGA' ... ]]
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
multiprocess:
- args: function (..., envir = parent.frame(), workers = 5)
- tweaked: TRUE
- call: plan("multiprocess", workers = 5)
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)
Matrix products: default
BLAS/LAPACK: /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/imkl/2018.3.222/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/l>

locale:
 [1] LC_CTYPE=en_US.UTF-8	LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8	LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] Matrix_1.2-18                     harmony_1.0
 [3] Rcpp_1.0.5                        patchwork_1.1.1
 [5] ggplot2_3.3.3                     BSgenome.Hsapiens.UCSC.hg38_1.4.1
 [7] BSgenome_1.54.0                   rtracklayer_1.46.0
 [9] Biostrings_2.54.0                 XVector_0.26.0
[11] EnsDb.Hsapiens.v86_2.99.0         ensembldb_2.10.2
[13] AnnotationFilter_1.10.0           GenomicFeatures_1.38.2
[15] AnnotationDbi_1.48.0              Biobase_2.46.0
[17] future_1.21.0                     GenomicRanges_1.38.0
[19] GenomeInfoDb_1.22.1               IRanges_2.20.2
[21] S4Vectors_0.24.4                  BiocGenerics_0.32.0
[23] Seurat_3.2.1                      Signac_1.1.0
loaded via a namespace (and not attached):
  [1] reticulate_1.18             tidyselect_1.1.0
  [3] RSQLite_2.2.0               htmlwidgets_1.5.3
  [5] grid_3.6.1                  BiocParallel_1.20.1
  [7] Rtsne_0.15                  munsell_0.5.0
  [9] codetools_0.2-16            ica_1.0-2
 [11] miniUI_0.1.1.1              withr_2.3.0
 [13] colorspace_2.0-0            OrganismDbi_1.28.0
 [15] knitr_1.29                  rstudioapi_0.13
 [17] ROCR_1.0-11                 tensor_1.5
 [19] listenv_0.8.0               GenomeInfoDbData_1.2.2
 [21] polyclip_1.10-0             bit64_0.9-7
 [23] farver_2.0.3                parallelly_1.23.0
 [25] vctrs_0.3.6                 generics_0.1.0
 [27] xfun_0.15                   biovizBase_1.34.1
 [29] BiocFileCache_1.10.2        lsa_0.73.2
 [31] ggseqlogo_0.1               R6_2.5.0
 [33] rsvd_1.0.3                  bitops_1.0-6
 [35] spatstat.utils_1.20-2	  reshape_0.8.8
 [37] DelayedArray_0.12.3         assertthat_0.2.1
 [39] promises_1.1.1              scales_1.1.1
 [41] nnet_7.3-12                 gtable_0.3.0
 [43] globals_0.14.0              goftest_1.2-2
 [45] ggbio_1.34.0                rlang_0.4.10
 [47] RcppRoll_0.3.0              splines_3.6.1
 [49] lazyeval_0.2.2              acepack_1.4.1
 [51] dichromat_2.0-0             checkmate_2.0.0
 [53] BiocManager_1.30.10         reshape2_1.4.4
 [55] abind_1.4-5                 backports_1.1.8
 [57] httpuv_1.5.4                Hmisc_4.4-0
 [59] RBGL_1.62.1                 tools_3.6.1
 [61] ellipsis_0.3.1              RColorBrewer_1.1-2
[63] ggridges_0.5.3              plyr_1.8.6
 [65] base64enc_0.1-3             progress_1.2.2
 [67] zlibbioc_1.32.0             purrr_0.3.4
 [69] RCurl_1.98-1.2              prettyunits_1.1.1
 [71] rpart_4.1-15                openssl_1.4.3
 [73] deldir_0.2-3                pbapply_1.4-3
 [75] cowplot_1.1.1               zoo_1.8-8
 [77] SummarizedExperiment_1.16.1 ggrepel_0.9.0
 [79] cluster_2.1.0               magrittr_2.0.1
 [81] data.table_1.13.6           lmtest_0.9-38
 [83] RANN_2.6.1                  SnowballC_0.7.0
 [85] ProtGenerics_1.18.0         fitdistrplus_1.1-3
 [87] matrixStats_0.57.0          hms_0.5.3
 [89] mime_0.9                    xtable_1.8-4
 [91] XML_3.99-0.3                jpeg_0.1-8.1
 [93] gridExtra_2.3               compiler_3.6.1
 [95] biomaRt_2.42.1              tibble_3.0.4
 [97] KernSmooth_2.23-15          crayon_1.3.4
 [99] htmltools_0.5.1.1           mgcv_1.8-28
[101] later_1.1.0.1               Formula_1.2-3
[103] tidyr_1.1.2                 DBI_1.1.0
[105] tweenr_1.0.1                dbplyr_1.4.4
[107] MASS_7.3-51.4               rappdirs_0.3.1
[109] igraph_1.2.6                pkgconfig_2.0.3
[111] GenomicAlignments_1.22.1    foreign_0.8-71
[113] plotly_4.9.3                stringr_1.4.0
[115] VariantAnnotation_1.32.0    digest_0.6.27
[117] sctransform_0.3.2           RcppAnnoy_0.0.18
[119] graph_1.64.0                spatstat.data_1.7-0
[121] leiden_0.3.6                fastmatch_1.1-0
[123] htmlTable_2.0.1             uwot_0.1.10
[125] curl_4.3                    shiny_1.5.0
[127] Rsamtools_2.2.3             lifecycle_0.2.0
[129] nlme_3.1-140                jsonlite_1.7.2
[131] viridisLite_0.3.0           askpass_1.1
[133] pillar_1.4.7                lattice_0.20-38
[135] GGally_2.0.0                fastmap_1.0.1
[137] httr_1.4.2                  survival_3.2-3
[139] glue_1.4.2                  spatstat_1.64-1
[141] png_0.1-7                   bit_1.1-15.2
[143] ggforce_0.3.2               stringi_1.5.3
[145] blob_1.2.1                  latticeExtra_0.6-29
[147] memoise_1.1.0               dplyr_1.0.2
[149] irlba_2.3.3                 future.apply_1.7.0
6 x 6105920 sparse Matrix of class "dgCMatrix"

chr1-1-1000    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1-1001-2000 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1-2001-3000 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1-3001-4000 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1-4001-5000 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1-5001-6000 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

chr1-1-1000    . . ......
chr1-1001-2000 . . ......
chr1-2001-3000 . . ......
chr1-3001-4000 . . ......
chr1-4001-5000 . . ......
chr1-5001-6000 . . ......
 .....suppressing 6105886 columns in show(); maybe adjust 'options(max.print= *, width = *)'
 ..............................
[1] 3099814 6105920

In the last line you see the dim(atac.bins) which is way more than cells present (6000)

**Comment by timoast** [comment] 2021-06-10 15:16
You seem to be looking at the dimension of a different matrix (`dim(atac6310.bins)`). What is the dimension of the output from the function: `dim(atac.bins)`?

**Comment by AnjaliC4** [comment] 2021-06-10 15:24
Hi Tim, I can confirm that I looked at dim(atac.bins). For the purpose of illustration, I changed the name of the matrix.

**Comment by timoast** [comment] 2021-06-10 15:44
I still can't reproduce this, and looking at the code the `cells` parameter is definitely being passed inside the `GenomeBinMatrix()` function. I'd suggest restarting R, clearing the environment, and making a minimal reproducible example that you can share

**Comment by timoast** [comment] 2021-06-23 13:39
Closing this now, feel free to reopen if you're still having issues

**Closed by timoast** 2021-06-23 13:39 UTC
Labels: bug
