### ISSUE TITLE
'No matching chromosomes found in fragment file' when running GeneActivity

### ISSUE THREAD

**Issue by Telogen** [timoast/signac#921] opened 2021-12-17 12:53 UTC
Hi Tim,
When I run GeneActivity(), I got the following error:
```
Error in SingleFeatureMatrix(fragment = fragments[[x]], features = features, : No matching chromosomes found in fragment file.
Traceback:

1. GeneActivity(pbmc.ATAC)
2. FeatureMatrix(fragments = frags, features = transcripts, cells = cells, 
 .     verbose = verbose, ...)
3. sapply(X = obj.use, FUN = function(x) {
 .     SingleFeatureMatrix(fragment = fragments[[x]], features = features, 
 .         cells = cells, sep = sep, verbose = verbose, process_n = process_n)
 . })
4. lapply(X = X, FUN = FUN, ...)
5. FUN(X[[i]], ...)
6. SingleFeatureMatrix(fragment = fragments[[x]], features = features, 
 .     cells = cells, sep = sep, verbose = verbose, process_n = process_n)
7. stop("No matching chromosomes found in fragment file.")
```

My codes are as follows
```r
chrom_assay <- CreateChromatinAssay(brain_peak_counts,sep = c("_", "_"),fragments = brain_fragment,genome = 'mm10')
pbmc.ATAC <- CreateSeuratObject(chrom_assay,assay = "ATAC")
library(EnsDb.Mmusculus.v79)
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79)
genome(annotations) <- "mm10"
seqlevelsStyle(annotations) <- 'UCSC'
# When I change the order of the above two lines, my R kernel will crash down :(
Annotation(pbmc.ATAC) <- annotations
gene.activities <- GeneActivity(pbmc.ATAC)
```

And the output of `Annotation(pbmc.ATAC)`:
```
GRanges object with 1763965 ranges and 5 metadata columns:
                     seqnames          ranges strand |              tx_id
                        <Rle>       <IRanges>  <Rle> |        <character>
  ENSMUSE00001236884        3 3508030-3508332      + | ENSMUST00000108393
  ENSMUSE00000676606        3 3634150-3634347      + | ENSMUST00000108394
  ENSMUSE00001345708        3 3638059-3638230      + | ENSMUST00000108393
  ENSMUSE00001345708        3 3638059-3638230      + | ENSMUST00000108394
  ENSMUSE00000149313        3 3641223-3641317      + | ENSMUST00000108393
                 ...      ...             ...    ... .                ...
  ENSMUST00000082414       MT     10167-11544      + | ENSMUST00000082414
  ENSMUST00000082418       MT     11742-13565      + | ENSMUST00000082418
  ENSMUST00000082419       MT     13552-14070      - | ENSMUST00000082419
  ENSMUST00000082421       MT     14145-15288      + | ENSMUST00000082421
  ENSMUST00000084013       MT      9877-10173      + | ENSMUST00000084013
                       gene_name            gene_id   gene_biotype     type
                     <character>        <character>    <character> <factor>
  ENSMUSE00001236884       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00000676606       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00001345708       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00001345708       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00000149313       Hnf4g ENSMUSG00000017688 protein_coding     exon
                 ...         ...                ...            ...      ...
  ENSMUST00000082414      mt-Nd4 ENSMUSG00000064363 protein_coding      cds
  ENSMUST00000082418      mt-Nd5 ENSMUSG00000064367 protein_coding      cds
  ENSMUST00000082419      mt-Nd6 ENSMUSG00000064368 protein_coding      cds
  ENSMUST00000082421     mt-Cytb ENSMUSG00000064370 protein_coding      cds
  ENSMUST00000084013     mt-Nd4l ENSMUSG00000065947 protein_coding      cds
  -------
  seqinfo: 22 sequences from mm10 genome
```

The output of `head(Fragments(pbmc.ATAC)[[1]])`:
```
  chrom   start     end                 barcode readCount
1  chr1 3000818 3000853 R1.50.R2.21.R3.09.P1.32         2
2  chr1 3000818 3000993 R1.54.R2.21.R3.15.P1.31         2
3  chr1 3001340 3001387 R1.30.R2.08.R3.93.P1.32         2
4  chr1 3001778 3001972 R1.49.R2.27.R3.66.P1.32         2
5  chr1 3003371 3003431 R1.37.R2.23.R3.68.P1.32         2
6  chr1 3003507 3003923 R1.08.R2.19.R3.89.P1.32         2
```

The output of `sessionInfo()`
```r
R version 4.1.0 (2021-05-18)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /local/txm/anaconda3/envs/R4.1/lib/libopenblasp-r0.3.17.so

locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] EnsDb.Mmusculus.v79_2.99.0 EnsDb.Mmusculus.v75_2.99.0
 [3] ensembldb_2.18.2           AnnotationFilter_1.18.0
 [5] GenomicFeatures_1.46.1     AnnotationDbi_1.56.2
 [7] Biobase_2.54.0             GenomicRanges_1.46.1
 [9] GenomeInfoDb_1.30.0        IRanges_2.28.0
[11] S4Vectors_0.32.3           BiocGenerics_0.40.0
[13] Matrix_1.4-0               ggplot2_3.3.5
[15] SeuratObject_4.0.4         Seurat_4.0.6
[17] Signac_1.5.0

loaded via a namespace (and not attached):
  [1] utf8_1.2.2                  reticulate_1.22
  [3] tidyselect_1.1.1            RSQLite_2.2.9
  [5] htmlwidgets_1.5.4           grid_4.1.0
  [7] docopt_0.7.1                BiocParallel_1.28.3
  [9] Rtsne_0.15                  munsell_0.5.0
 [11] codetools_0.2-18            ica_1.0-2
 [13] future_1.23.0               miniUI_0.1.1.1
 [15] withr_2.4.3                 colorspace_2.0-2
 [17] filelock_1.0.2              knitr_1.37
 [19] rstudioapi_0.13             ROCR_1.0-11
 [21] tensor_1.5                  listenv_0.8.0
 [23] MatrixGenerics_1.6.0        slam_0.1-49
 [25] GenomeInfoDbData_1.2.7      polyclip_1.10-0
 [27] bit64_4.0.5                 farver_2.1.0
 [29] parallelly_1.30.0           vctrs_0.3.8
 [31] generics_0.1.1              xfun_0.29
 [33] biovizBase_1.42.0           BiocFileCache_2.2.0
 [35] lsa_0.73.2                  ggseqlogo_0.1
 [37] R6_2.5.1                    bitops_1.0-7
 [39] spatstat.utils_2.3-0        cachem_1.0.6
 [41] DelayedArray_0.20.0         assertthat_0.2.1
 [43] promises_1.2.0.1            BiocIO_1.4.0
 [45] scales_1.1.1                nnet_7.3-16
 [47] gtable_0.3.0                globals_0.14.0
 [49] goftest_1.2-3               rlang_0.4.12
 [51] RcppRoll_0.3.0              splines_4.1.0
 [53] rtracklayer_1.54.0          lazyeval_0.2.2
 [55] dichromat_2.0-0             checkmate_2.0.0
 [57] spatstat.geom_2.3-1         yaml_2.2.1
 [59] reshape2_1.4.4              abind_1.4-5
 [61] backports_1.4.1             httpuv_1.6.4
 [63] Hmisc_4.6-0                 tools_4.1.0
 [65] ellipsis_0.3.2              spatstat.core_2.3-2
 [67] RColorBrewer_1.1-2          ggridges_0.5.3                                                                                                                                                            
 [69] Rcpp_1.0.7                  plyr_1.8.6
 [71] base64enc_0.1-3             progress_1.2.2
 [73] zlibbioc_1.40.0             purrr_0.3.4
 [75] RCurl_1.98-1.5              prettyunits_1.1.1
 [77] rpart_4.1-15                deldir_1.0-6
 [79] pbapply_1.5-0               cowplot_1.1.1
 [81] zoo_1.8-9                   SummarizedExperiment_1.24.0
 [83] ggrepel_0.9.1               cluster_2.1.2
 [85] magrittr_2.0.1              data.table_1.14.2
 [87] scattermore_0.7             lmtest_0.9-39
 [89] RANN_2.6.1                  SnowballC_0.7.0
 [91] ProtGenerics_1.26.0         fitdistrplus_1.1-6
 [93] matrixStats_0.61.0          hms_1.1.1
 [95] patchwork_1.1.1             mime_0.12
 [97] xtable_1.8-4                XML_3.99-0.8
 [99] jpeg_0.1-9                  sparsesvd_0.2
[101] gridExtra_2.3               compiler_4.1.0
[103] biomaRt_2.50.1              tibble_3.1.6
[105] KernSmooth_2.23-20          crayon_1.4.2
[107] htmltools_0.5.2             mgcv_1.8-38
[109] later_1.3.0                 Formula_1.2-4
[111] tidyr_1.1.4                 DBI_1.1.1
[113] tweenr_1.0.2                dbplyr_2.1.1
[115] MASS_7.3-54                 rappdirs_0.3.3
[117] parallel_4.1.0              igraph_1.2.10
[119] pkgconfig_2.0.3             GenomicAlignments_1.30.0
[121] foreign_0.8-81              plotly_4.10.0
[123] spatstat.sparse_2.1-0       xml2_1.3.3
[125] XVector_0.34.0              VariantAnnotation_1.40.0
[127] stringr_1.4.0               digest_0.6.29
[129] sctransform_0.3.2           RcppAnnoy_0.0.19
[131] spatstat.data_2.1-2         Biostrings_2.62.0
[133] leiden_0.3.9                fastmatch_1.1-3
[135] htmlTable_2.3.0             uwot_0.1.11
[137] restfulr_0.0.13             curl_4.3.2
[139] shiny_1.7.1                 Rsamtools_2.10.0
[141] rjson_0.2.20                lifecycle_1.0.1
[143] nlme_3.1-153                jsonlite_1.7.2
[145] BSgenome_1.62.0             viridisLite_0.4.0
[147] fansi_0.5.0                 pillar_1.6.4
[149] lattice_0.20-45             KEGGREST_1.34.0
[151] fastmap_1.1.0               httr_1.4.2
[153] survival_3.2-13             glue_1.6.0
[155] qlcMatrix_0.9.7             png_0.1-7
[157] bit_4.0.4                   ggforce_0.3.3
[159] stringi_1.7.6               blob_1.2.2
[161] latticeExtra_0.6-29         memoise_2.0.1
[163] dplyr_1.0.7                 irlba_2.3.5
[165] future.apply_1.8.1
```

Looking forward to your help. Many thanks!

**Comment by timoast** [comment] 2021-12-17 13:51
The problem is the chromosome names in the annotation and fragment file do not match. Try removing the line `genome(annotations) <- "mm10"`

**Comment by Telogen** [comment] 2021-12-17 14:14
Thanks for your reply, unnfortunately, my R kernel crashed down when I removing the line `genome(annotations) <- "mm10"`:
```

 *** caught segfault ***
address 0xffffffffdd444ce0, cause 'memory not mapped'

Traceback:
 1: curlPerform(curl = curl, .opts = opts, .encoding = .encoding)
 2: getURL(url)
 3: list_ftp_dir(url)
 4: .form_assembly_report_url(assembly_accession)
 5: fetch_assembly_report(accession)
 6: .get_NCBI_chrom_info_from_accession(accession, circ_seqs = circ_seqs,     assembled.molecules.only = assembled.molecules.only, assembly.units = assembly.units,     recache = recache)
 7: getChromInfoFromNCBI(assembly_accession, assembly.units = AssemblyUnits)
 8: (function (UCSC_chrom_info, assembly_accession, AssemblyUnits = NULL,     special_mappings = NULL, unmapped_seqs = NULL, drop_unmapped = FALSE) {    UCSC_seqlevels <- UCSC_chrom_info[, "chrom"]    if (length(
unmapped_seqs) != 0L) {        unmapped_seqs_role <- rep.int(names(unmapped_seqs), lengths(unmapped_seqs))        unmapped_seqs <- unlist(unmapped_seqs, use.names = FALSE)        unmapped_idx <- match(unmapped_se
qs, UCSC_seqlevels)        stopifnot(!anyNA(unmapped_idx))    }    NCBI_chrom_info <- getChromInfoFromNCBI(assembly_accession,         assembly.units = AssemblyUnits)    NCBI_seqlevels <- NCBI_chrom_info[, "Seque
nceName"]    NCBI_UCSCStyleName <- NCBI_chrom_info[, "UCSCStyleName"]    NCBI_GenBankAccn <- NCBI_chrom_info[, "GenBankAccn"]    NCBI_RefSeqAccn <- NCBI_chrom_info[, "RefSeqAccn"]    L2R <- .map_UCSC_seqlevels_to
_NCBI_seqlevels(UCSC_seqlevels,         NCBI_seqlevels, NCBI_UCSCStyleName, NCBI_GenBankAccn,         NCBI_RefSeqAccn, special_mappings = special_mappings)    L2R_is_NA <- is.na(L2R)    mapped_idx <- which(!L2R_i
s_NA)    if (length(unmapped_seqs) != 0L)         stopifnot(all(L2R_is_NA[unmapped_idx]))    if (isTRUE(drop_unmapped)) {        UCSC_chrom_info <- S4Vectors:::extract_data_frame_rows(UCSC_chrom_info,
 mapped_idx)        L2R <- L2R[mapped_idx]        mapped_idx <- seq_along(L2R)        idx <- setdiff(seq_along(NCBI_seqlevels), L2R)        if (length(idx) != 0L) {            in1string <- paste0(NCBI_seqlevels[i
dx], collapse = ", ")            stop(wmsg("no UCSC seqlevel could be mapped to the following ",                 "NCBI seqlevel(s): ", in1string))        }    }    else {        unexpectedly_unmapped_idx <- which
(L2R_is_NA & !(UCSC_seqlevels %in%             unmapped_seqs))        if (length(unexpectedly_unmapped_idx) != 0L) {            in1string <- paste0(UCSC_seqlevels[unexpectedly_unmapped_idx],                 colla
pse = ", ")            stop(wmsg("cannot map the following UCSC seqlevel(s) to an ",                 "NCBI seqlevel: ", in1string))        }    }    NCBI_chrom_info <- S4Vectors:::extract_data_frame_rows(NCBI_chr
om_info,         L2R)    stopifnot(identical(UCSC_chrom_info[mapped_idx, "circular"],         NCBI_chrom_info[mapped_idx, "circular"]))    compare_idx <- which(!is.na(NCBI_chrom_info[, "SequenceLength"]))    stop
ifnot(identical(UCSC_chrom_info[compare_idx, "size"],         NCBI_chrom_info[compare_idx, "SequenceLength"]))    if (assembly_accession != "GCF_000001405.25") {        compare_idx <- which(!is.na(NCBI_chrom_info
[, "UCSCStyleName"]))        x <- UCSC_chrom_info[compare_idx, "chrom"]        y <- NCBI_chrom_info[compare_idx, "UCSCStyleName"]        if (assembly_accession == "GCF_000001635.26") {            i1 <- match("chr
9_KB469738_fix", x)            i2 <- match("chr9_KB469738v3_fix", y)            stopifnot(isFALSE(is.na(i1)), isFALSE(is.na(i2)),                 identical(i1, i2))            x <- x[-i1]            y <- y[-i2]
      }        stopifnot(identical(x, y))    }    drop_columns <- c("SequenceLength", "UCSCStyleName", "circular")    NCBI_chrom_info <- drop_cols(NCBI_chrom_info, drop_columns)    colnames(NCBI_chrom_info) <- pa
ste0("NCBI.", colnames(NCBI_chrom_info))    ans <- cbind(UCSC_chrom_info, NCBI_chrom_info)    if (length(unmapped_seqs) != 0L)         ans[unmapped_idx, "NCBI.SequenceRole"] <- unmapped_seqs_role    stopifnot(!is
.unsorted(ans[, "NCBI.SequenceRole"]))    ans})(list(chrom = c("chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr1
8", "chr19", "chrX", "chrY", "chrM", "chr1_GL455991_alt", "chr1_GL455992_alt", "chr1_GL455993_alt", "chr1_GL456005_alt", "chr1_JH584315_alt", "chr1_JH584320_alt", "chr1_JH584321_alt", "chr1_JH584322_alt", "chr2_G
L456024_alt", "chr3_GL456006_alt", "chr3_GL456007_alt", "chr3_GL456008_alt", "chr3_GL456042_alt", "chr3_GL456044_alt", "chr3_GL456045_alt", "chr3_GL456048_alt", "chr3_GL456049_alt", "chr3_JH584323_alt", "chr4_GL4
55994_alt", "chr4_GL456009_alt", "chr4_GL456010_alt", "chr4_GL456053_alt", "chr4_GL456064_alt", "chr4_GL456075_alt", "chr4_GL456076_alt", "chr4_GL456077_alt", "chr4_JH584268_alt", "chr4_JH584269_alt", "chr4_JH584
324_alt", "chr4_JH584325_alt", "chr4_JH584326_alt", "chr5_GL455995_alt", "chr5_GL456011_alt", "chr6_GL456012_alt", "chr6_GL456025_alt", "chr6_GL456026_alt", "chr6_GL456054_alt", "chr6_GL456065_alt", "chr6_JH58426
4_alt", "chr7_GL455989_alt", "chr7_GL456013_alt", "chr7_GL456014_alt", "chr8_GL455996_alt", "chr8_GL455997_alt", "chr10_GL456015_alt", "chr11_GL455998_alt", "chr11_GL456016_alt", "chr11_GL456060_alt", "chr11_JH58
4265_alt", "chr11_JH584316_alt", "chr11_JH584317_alt", "chr11_JH584327_alt", "chr12_GL456017_alt", "chr12_GL456068_alt", "chr12_GL456074_alt", "chr12_GL456078_alt", "chr12_GL456349_alt", "chr13_GL455990_alt", "ch
r13_GL455999_alt", "chr13_JH584305_alt", "chr14_GL456019_alt", "chr14_GL456020_alt", "chr15_GL456000_alt", "chr15_JH584270_alt", "chr16_GL456001_alt", "chr16_GL456028_alt", "chr16_JH584306_alt", "chr16_JH584307_a
lt", "chr16_JH584310_alt", "chr16_JH584311_alt", "chr16_JH584312_alt", "chr16_JH584313_alt", "chr16_JH584314_alt", "chr17_GL456002_alt", "chr17_GL456021_alt", "chr17_GL456022_alt", "chr17_GL456069_alt", "chr17_JH
584266_alt", "chr17_JH584267_alt"

(too much to paste)
```

**Comment by Telogen** [comment] 2021-12-17 14:14
Thanks for your reply, unnfortunately, my R kernel crashed down when I removing the line `genome(annotations) <- "mm10"`:
```

 *** caught segfault ***
address 0xffffffffdd444ce0, cause 'memory not mapped'

Traceback:
 1: curlPerform(curl = curl, .opts = opts, .encoding = .encoding)
 2: getURL(url)
 3: list_ftp_dir(url)
 4: .form_assembly_report_url(assembly_accession)
 5: fetch_assembly_report(accession)
 6: .get_NCBI_chrom_info_from_accession(accession, circ_seqs = circ_seqs,     assembled.molecules.only = assembled.molecules.only, assembly.units = assembly.units,     recache = recache)
 7: getChromInfoFromNCBI(assembly_accession, assembly.units = AssemblyUnits)
 8: (function (UCSC_chrom_info, assembly_accession, AssemblyUnits = NULL,     special_mappings = NULL, unmapped_seqs = NULL, drop_unmapped = FALSE) {    UCSC_seqlevels <- UCSC_chrom_info[, "chrom"]    if (length(
unmapped_seqs) != 0L) {        unmapped_seqs_role <- rep.int(names(unmapped_seqs), lengths(unmapped_seqs))        unmapped_seqs <- unlist(unmapped_seqs, use.names = FALSE)        unmapped_idx <- match(unmapped_se
qs, UCSC_seqlevels)        stopifnot(!anyNA(unmapped_idx))    }    NCBI_chrom_info <- getChromInfoFromNCBI(assembly_accession,         assembly.units = AssemblyUnits)    NCBI_seqlevels <- NCBI_chrom_info[, "Seque
nceName"]    NCBI_UCSCStyleName <- NCBI_chrom_info[, "UCSCStyleName"]    NCBI_GenBankAccn <- NCBI_chrom_info[, "GenBankAccn"]    NCBI_RefSeqAccn <- NCBI_chrom_info[, "RefSeqAccn"]    L2R <- .map_UCSC_seqlevels_to
_NCBI_seqlevels(UCSC_seqlevels,         NCBI_seqlevels, NCBI_UCSCStyleName, NCBI_GenBankAccn,         NCBI_RefSeqAccn, special_mappings = special_mappings)    L2R_is_NA <- is.na(L2R)    mapped_idx <- which(!L2R_i
s_NA)    if (length(unmapped_seqs) != 0L)         stopifnot(all(L2R_is_NA[unmapped_idx]))    if (isTRUE(drop_unmapped)) {        UCSC_chrom_info <- S4Vectors:::extract_data_frame_rows(UCSC_chrom_info,
 mapped_idx)        L2R <- L2R[mapped_idx]        mapped_idx <- seq_along(L2R)        idx <- setdiff(seq_along(NCBI_seqlevels), L2R)        if (length(idx) != 0L) {            in1string <- paste0(NCBI_seqlevels[i
dx], collapse = ", ")            stop(wmsg("no UCSC seqlevel could be mapped to the following ",                 "NCBI seqlevel(s): ", in1string))        }    }    else {        unexpectedly_unmapped_idx <- which
(L2R_is_NA & !(UCSC_seqlevels %in%             unmapped_seqs))        if (length(unexpectedly_unmapped_idx) != 0L) {            in1string <- paste0(UCSC_seqlevels[unexpectedly_unmapped_idx],                 colla
pse = ", ")            stop(wmsg("cannot map the following UCSC seqlevel(s) to an ",                 "NCBI seqlevel: ", in1string))        }    }    NCBI_chrom_info <- S4Vectors:::extract_data_frame_rows(NCBI_chr
om_info,         L2R)    stopifnot(identical(UCSC_chrom_info[mapped_idx, "circular"],         NCBI_chrom_info[mapped_idx, "circular"]))    compare_idx <- which(!is.na(NCBI_chrom_info[, "SequenceLength"]))    stop
ifnot(identical(UCSC_chrom_info[compare_idx, "size"],         NCBI_chrom_info[compare_idx, "SequenceLength"]))    if (assembly_accession != "GCF_000001405.25") {        compare_idx <- which(!is.na(NCBI_chrom_info
[, "UCSCStyleName"]))        x <- UCSC_chrom_info[compare_idx, "chrom"]        y <- NCBI_chrom_info[compare_idx, "UCSCStyleName"]        if (assembly_accession == "GCF_000001635.26") {            i1 <- match("chr
9_KB469738_fix", x)            i2 <- match("chr9_KB469738v3_fix", y)            stopifnot(isFALSE(is.na(i1)), isFALSE(is.na(i2)),                 identical(i1, i2))            x <- x[-i1]            y <- y[-i2]
      }        stopifnot(identical(x, y))    }    drop_columns <- c("SequenceLength", "UCSCStyleName", "circular")    NCBI_chrom_info <- drop_cols(NCBI_chrom_info, drop_columns)    colnames(NCBI_chrom_info) <- pa
ste0("NCBI.", colnames(NCBI_chrom_info))    ans <- cbind(UCSC_chrom_info, NCBI_chrom_info)    if (length(unmapped_seqs) != 0L)         ans[unmapped_idx, "NCBI.SequenceRole"] <- unmapped_seqs_role    stopifnot(!is
.unsorted(ans[, "NCBI.SequenceRole"]))    ans})(list(chrom = c("chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr1
8", "chr19", "chrX", "chrY", "chrM", "chr1_GL455991_alt", "chr1_GL455992_alt", "chr1_GL455993_alt", "chr1_GL456005_alt", "chr1_JH584315_alt", "chr1_JH584320_alt", "chr1_JH584321_alt", "chr1_JH584322_alt", "chr2_G
L456024_alt", "chr3_GL456006_alt", "chr3_GL456007_alt", "chr3_GL456008_alt", "chr3_GL456042_alt", "chr3_GL456044_alt", "chr3_GL456045_alt", "chr3_GL456048_alt", "chr3_GL456049_alt", "chr3_JH584323_alt", "chr4_GL4
55994_alt", "chr4_GL456009_alt", "chr4_GL456010_alt", "chr4_GL456053_alt", "chr4_GL456064_alt", "chr4_GL456075_alt", "chr4_GL456076_alt", "chr4_GL456077_alt", "chr4_JH584268_alt", "chr4_JH584269_alt", "chr4_JH584
324_alt", "chr4_JH584325_alt", "chr4_JH584326_alt", "chr5_GL455995_alt", "chr5_GL456011_alt", "chr6_GL456012_alt", "chr6_GL456025_alt", "chr6_GL456026_alt", "chr6_GL456054_alt", "chr6_GL456065_alt", "chr6_JH58426
4_alt", "chr7_GL455989_alt", "chr7_GL456013_alt", "chr7_GL456014_alt", "chr8_GL455996_alt", "chr8_GL455997_alt", "chr10_GL456015_alt", "chr11_GL455998_alt", "chr11_GL456016_alt", "chr11_GL456060_alt", "chr11_JH58
4265_alt", "chr11_JH584316_alt", "chr11_JH584317_alt", "chr11_JH584327_alt", "chr12_GL456017_alt", "chr12_GL456068_alt", "chr12_GL456074_alt", "chr12_GL456078_alt", "chr12_GL456349_alt", "chr13_GL455990_alt", "ch
r13_GL455999_alt", "chr13_JH584305_alt", "chr14_GL456019_alt", "chr14_GL456020_alt", "chr15_GL456000_alt", "chr15_JH584270_alt", "chr16_GL456001_alt", "chr16_GL456028_alt", "chr16_JH584306_alt", "chr16_JH584307_a
lt", "chr16_JH584310_alt", "chr16_JH584311_alt", "chr16_JH584312_alt", "chr16_JH584313_alt", "chr16_JH584314_alt", "chr17_GL456002_alt", "chr17_GL456021_alt", "chr17_GL456022_alt", "chr17_GL456069_alt", "chr17_JH
584266_alt", "chr17_JH584267_alt"

(too much to paste)
```

**Comment by timoast** [comment] 2021-12-17 15:41
This looks like an issue with the GenomeInfoDb package, I'd suggest reinstalling GenomeInfoDb and restarting R and see if you still have this issue. If so, you should ask for help on the bioconductor support site.

The reason for the Signac error is that the chromosome names don't match across the fragment file and gene annotations, so I will close this issue.

**Closed by timoast** 2021-12-17 15:41 UTC
