### ISSUE TITLE
Error in DietSeurat(object = object.list[[i]], assays = assay[i], features = anchor.features,  :    The default assay is slated to be removed, please change the default assay

### ISSUE THREAD

**Issue by sqs1020** [timoast/signac#898] opened 2021-12-07 02:43 UTC
Hello,

I am trying to integrate my 6 scATACseq samples. I made a list for them and used FindIntegrationAnchors below 
integration.anchors <- FindIntegrationAnchors(
  object.list = PA.list,
  anchor.features = features,
  reduction = "rlsi",
  dims = 2:30
)
And I got error like this
![image](https://user-images.githubusercontent.com/52260392/144956573-f889db29-2197-4fa8-a414-9ae35e64c27c.png)
![image](https://user-images.githubusercontent.com/52260392/144957059-39ff01bb-6f71-4314-929b-66b166d845e3.png)

Could you help me with this ? 

Thanks!

**Comment by timoast** [comment] 2021-12-08 16:41
Duplicate of https://github.com/satijalab/seurat/issues/5370

**Closed by timoast** 2021-12-08 16:41 UTC

**Comment by sqs1020** [comment] 2021-12-08 19:35
Hi, I am sorry don't know it would be marked dupilcate between signac and seurat. I asked here in signac and no response so that also posted on seurat later. Sorry for the duplication. And could you please help me with the problem? Thanks!

> Duplicate of [satijalab/seurat#5370](https://github.com/satijalab/seurat/issues/5370)
