### ISSUE TITLE
Seg fault in peak calling

### ISSUE THREAD

**Issue by celalp** [timoast/signac#703] opened 2021-07-07 14:37 UTC
Hi, 

I'm trying to use the CallPeaks function but getting the following error. I've tried different versions of Signac but no luck. This seems like an error similar to [this](https://stackoverflow.com/questions/49190251/caught-segfault-memory-not-mapped-error-in-r) but the fact that I'm getting `0x0` is a little more suspicious. 

The code is straight forward. 

```r
library(Signac)
library(Seurat)
library(dplyr)

brain_atac<-readRDS("atac.rds")

DefaultAssay(brain_atac)<-"peaks"

peaks <- CallPeaks(
  object = brain_atac,
  group.by = "manual_labels",
  macs2.path = "/Users/alper celik/Library/Python/3.9/bin/macs2"
)
```
And there is the segfault error:

```
Processing file fragments.tsv.gz
Keeping 38123 cell barcodes
Splitting into 19 files
Done Processing 281 million lines
 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: splitFragments(fragments = fragpath, outdir = paste0(outdir,     .Platform$file.sep), suffix = suffix.use, append = append,     cells = frag.cell.name, idents = idents.use, unique_idents = unique_idents,     buffer_length = buffer_length, verbose = verbose)
 2: SplitFragments(object = object, assay = assay, group.by = group.by,     idents = idents, outdir = tempdir(), verbose = verbose)
 3: CallPeaks.Seurat(object = brain_atac, group.by = "manual_labels",     macs2.path = "/Users/alper celik/Library/Python/3.9/bin/macs2")
 4: CallPeaks(object = brain_atac, group.by = "manual_labels", macs2.path = "/Users/alper celik/Library/Python/3.9/bin/macs2")
```

The computer is not running out of memory. I monitored the process with the system monitor the entire time. 

And here is the session info

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.7        SeuratObject_4.0.2 Seurat_4.0.3       Signac_1.2.0      

loaded via a namespace (and not attached):
  [1] Rtsne_0.15             colorspace_2.0-1       deldir_0.2-10          ellipsis_0.3.2        
  [5] ggridges_0.5.3         lsa_0.73.2             XVector_0.32.0         GenomicRanges_1.44.0  
  [9] rstudioapi_0.13        spatstat.data_2.1-0    farver_2.1.0           leiden_0.3.8          
 [13] listenv_0.8.0          SnowballC_0.7.0        ggrepel_0.9.1          fansi_0.5.0           
 [17] codetools_0.2-18       splines_4.1.0          docopt_0.7.1           RcppRoll_0.3.0        
 [21] polyclip_1.10-0        jsonlite_1.7.2         Rsamtools_2.8.0        ica_1.0-2             
 [25] cluster_2.1.2          png_0.1-7              uwot_0.1.10            ggforce_0.3.3         
 [29] shiny_1.6.0            sctransform_0.3.2      spatstat.sparse_2.0-0  compiler_4.1.0        
 [33] httr_1.4.2             assertthat_0.2.1       Matrix_1.3-3           fastmap_1.1.0         
 [37] lazyeval_0.2.2         tweenr_1.0.2           later_1.2.0            htmltools_0.5.1.1     
 [41] tools_4.1.0            igraph_1.2.6           gtable_0.3.0           glue_1.4.2            
 [45] GenomeInfoDbData_1.2.6 RANN_2.6.1             reshape2_1.4.4         fastmatch_1.1-0       
 [49] Rcpp_1.0.6             slam_0.1-48            scattermore_0.7        vctrs_0.3.8           
 [53] Biostrings_2.60.1      nlme_3.1-152           ggseqlogo_0.1          lmtest_0.9-38         
 [57] stringr_1.4.0          globals_0.14.0         mime_0.10              miniUI_0.1.1.1        
 [61] lifecycle_1.0.0        irlba_2.3.3            goftest_1.2-2          future_1.21.0         
 [65] zlibbioc_1.38.0        MASS_7.3-54            zoo_1.8-9              scales_1.1.1          
 [69] spatstat.core_2.2-0    promises_1.2.0.1       spatstat.utils_2.2-0   parallel_4.1.0        
 [73] RColorBrewer_1.1-2     reticulate_1.20        pbapply_1.4-3          gridExtra_2.3         
 [77] ggplot2_3.3.4          rpart_4.1-15           stringi_1.6.2          S4Vectors_0.30.0      
 [81] BiocGenerics_0.38.0    BiocParallel_1.26.0    GenomeInfoDb_1.28.0    rlang_0.4.11          
 [85] pkgconfig_2.0.3        matrixStats_0.59.0     bitops_1.0-7           qlcMatrix_0.9.7       
 [89] lattice_0.20-44        ROCR_1.0-11            purrr_0.3.4            tensor_1.5            
 [93] patchwork_1.1.1        htmlwidgets_1.5.3      cowplot_1.1.1          tidyselect_1.1.1      
 [97] parallelly_1.26.0      RcppAnnoy_0.0.18       plyr_1.8.6             magrittr_2.0.1        
[101] R6_2.5.0               IRanges_2.26.0         generics_0.1.0         DBI_1.1.1             
[105] mgcv_1.8-35            pillar_1.6.1           fitdistrplus_1.1-5     survival_3.2-11       
[109] abind_1.4-5            RCurl_1.98-1.3         tibble_3.1.2           future.apply_1.7.0    
[113] crayon_1.4.1           KernSmooth_2.23-20     utf8_1.2.1             spatstat.geom_2.2-0   
[117] plotly_4.9.4.1         grid_4.1.0             data.table_1.14.0      sparsesvd_0.2         
[121] digest_0.6.27          xtable_1.8-4           tidyr_1.1.3            httpuv_1.6.1          
[125] stats4_4.1.0           munsell_0.5.0          viridisLite_0.4.0     
```

I am getting the exact same error on a CentOS7 with R/4.0.0. 

Thanks

**Comment by timoast** [comment] 2021-07-07 16:09
Can you show the output of `table(brain_atac$manual_labels)`?

**Comment by celalp** [comment] 2021-07-07 16:24
Thanks for the quick response, here is the table

```
Astro          CA1_10          CA1_11          CA1_12           CA1_2           CA1_8           CA1_9 
           5203             809             586             567            4946            1027             975 
            CA3              DG            Endo           Lamp5       Micro_Pvm Oligo_pdgfra(-) Oligo_pdgfra(+) 
           3125           11001             342             510            1516            4315            1393 
          Pvalb            Sncg             Sst             Vip 
            593             262             549             369 
```

**Comment by timoast** [comment] 2021-07-07 20:29
I found one issue related to this, which would cause an error when the group names contain a special character (now fixed on develop branch). However, I don't think that was the cause of the issue here (although you would likely have hit it if not for this segfault).

I'm not able to reproduce the issue here, are you able to share the fragment file or a downsampled version that reproduces the error? You can email a link to tstuart@nygenome.org

**Comment by timoast** [comment] 2021-07-21 18:54
Closing this as I haven't heard anything from you, please reopen if you're still having issues and are able to provide the requested information

**Closed by timoast** 2021-07-21 18:54 UTC
Labels: bug
