### ISSUE TITLE
hi Tim,

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#53] opened 2019-12-30 12:04 UTC
I get some issue if i run signac on step:
VlnPlot(
  object = brain,
  features = c('pct_reads_in_peaks', 'blacklist_ratio', 'nucleosome_signal', 'peak_region_fragments'),
  pt.size = 0.1,
  ncol = 4) + NoLegend()
The nucleosome_signal had run over, but the plot show empty on it,the column had number and  I check the column'nucleosome_signal' name triple time, it's not worked , i don't know what happen for my analysis or this Vlnplot function? i hope you can help me to resolve this problem.Thank you.

**Comment by timoast** [comment] 2019-12-30 19:47
Hi Alec, can you post the full code you're running, the plot, and the plot generated by `hist(<object_name>$nucleosome_signal)`?

**Comment by honghh2018** [comment] 2019-12-31 01:19
The full code showing below:
merge_atac <- Read10X_h5("../../merge_multiple/merge/outs/filtered_peak_bc_matrix.h5")
metadata <- read.csv(
  file = "../../merge_multiple/merge/outs/singlecell.csv",
  header = TRUE,
  row.names = 1
)

testic <- CreateSeuratObject(counts =merge_atac ,assay = 'peaks',project = 'ATAC',min.cells = 1,meta.data = metadata)

fragment.path <- '../../merge_multiple/merge/outs/fragments.tsv.gz'

testic <- SetFragments(
  object = testic,
  file = fragment.path
)
View(testic@meta.data$nucleosome_signal)
testic <- NucleosomeSignal(object = testic) ###check nucleosome signal

testic$pct_reads_in_peaks <- testic$peak_region_fragments / testic$passed_filters * 100
testic$blacklist_ratio <- testic$blacklist_region_fragments / testic$peak_region_fragments
colnames(testic@meta.data)
###Vlnplot
VlnPlot(object = testic,features = c('pct_reads_in_peaks', 'blacklist_ratio', 'nucleosome_signal', 'peak_region_fragments'),
pt.size = 0.1,ncol = 4) + NoLegend()
I check the nucleosome_signal column, which including the number indeed. but VlnPlot function just plotting column, pct_reads_in_peaks, blacklist_ratio, peak_region_fragments, not plotting 'nucleosome_signal'.That is very weird. The column name have not incorrect with Vlnplot function's parameter features. That confuse me a lots.

**Comment by timoast** [comment] 2019-12-31 01:35
Thanks, can you post the plots I asked for too?

**Comment by honghh2018** [comment] 2019-12-31 01:40
hi,Tim
 The picture showing below:
![image](https://user-images.githubusercontent.com/41668708/71607075-54322680-2bb1-11ea-9f20-16ac06d8a6f5.png)
  The meta.data showing below:
   
![image](https://user-images.githubusercontent.com/41668708/71607095-8ba0d300-2bb1-11ea-926a-00b7df2701c2.png)

**Comment by timoast** [comment] 2019-12-31 01:47
What happens if you just try to plot `nucleosome_signal` by itself? Can you also try this:

```r
library(ggplot2)
ggplot(testic[[]], aes(x = orig.ident, y = nucleosome_signal)) + geom_violin()
```

**Comment by honghh2018** [comment] 2019-12-31 02:02
Thanks for your urgent answer, I would add the code you sent me to draw my plotting.
 But I just wonder why The function plotting, VlnPlot, merely not plotting the column nucleosome_signal. The other column like pct_reads_in_peaks and so on are normal.

**Comment by timoast** [comment] 2019-12-31 02:45
I realize that, I’m just trying to work out the problem. Can you show the output of the two things I suggested above?

**Comment by honghh2018** [comment] 2019-12-31 03:52
The full code:
####ATAC的signac
library(Signac)
library(ggplot2)
library(GenomeInfoDb)
library(EnsDb.Mmusculus.v79)
.libPaths(c('/share/nas2/public/R/library/3.6','/home/honghh/R/x86_64-redhat-linux-gnu-library/3.6'))
setwd('/share/nas1/Data/Users/honghh/ScRNA_Project/jida_project_data/39/ATAC_ChIP_Pipeline/2019-12-30')


merge_atac <- Read10X_h5("../../merge_multiple/merge/outs/filtered_peak_bc_matrix.h5")
metadata <- read.csv(
&nbsp; file = "../../merge_multiple/merge/outs/singlecell.csv",
&nbsp; header = TRUE,
&nbsp; row.names = 1
)


testic <- CreateSeuratObject(counts =merge_atac ,assay = 'ATAC',project = 'peak',min.cells = 1,meta.data = metadata)


fragment.path <- '../../merge_multiple/merge/outs/fragments.tsv.gz'


testic <- SetFragments(
&nbsp; object = testic,
&nbsp; file = fragment.path
)


testic <- NucleosomeSignal(object = testic) ###核小体信号捕获函数
###
testic$pct_reads_in_peaks <- testic$peak_region_fragments / testic$passed_filters * 100
testic$blacklist_ratio <- testic$blacklist_region_fragments / testic$peak_region_fragments


###Vlnplot
VlnPlot(object = testic,features = c('pct_reads_in_peaks', 'blacklist_ratio', 'nucleosome_signal', 'peak_region_fragments'),
pt.size = 0.1,ncol = 4)
ggplot(testic@meta.data, aes(x = orig.ident, y = nucleosome_signal)) + geom_violin() ###draw nucleosome_signal
VlnPlot(object = testic,features = c('nucleosome_percentile'),
&nbsp; &nbsp; &nbsp; &nbsp; pt.size = 0.1,ncol = 1) + NoLegend()


testic$nucleosome_group <- ifelse(testic$nucleosome_signal &gt; 10, 'NS &gt; 10', 'NS < 10')
PeriodPlot(object = testic, group.by = 'nucleosome_group', region = 'chr1-1-10000000')
####split suffix
gemgroup <- sapply(strsplit(rownames(testic@meta.data), split="-"), "[[", 2)&nbsp;
phentype<-data.frame(gemgroup=gemgroup, row.names=rownames(testic@meta.data))
testic <- AddMetaData(object=testic, metadata=data.frame(gemgroup=gemgroup, row.names=rownames(testic@meta.data)))



The VlnPlot picture:





the meta.data of nucleosome_signal plot:



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tim Stuart"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 上午10:45
收件人:&nbsp;"timoast/signac"<signac@noreply.github.com&gt;;
抄送:&nbsp;"洪汉辉"<939869915@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [timoast/signac] hi Tim, (#53)



I realize that, I’m just trying to work out the problem. Can you show the output of the two things I suggested above?

**Comment by timoast** [comment] 2019-12-31 03:57
You can't attach image via email you'll need to do it though github. I'd just like to see the output from:

```r
VlnPlot(testic, 'nucleosome_signal')
library(ggplot2)
ggplot(testic[[]], aes(x = orig.ident, y = nucleosome_signal)) + geom_violin()
```

**Comment by honghh2018** [comment] 2019-12-31 04:10
ggplot(testic[[]], aes(x = orig.ident, y = nucleosome_signal)) + geom_violin() drawing plots like below:
![image](https://user-images.githubusercontent.com/41668708/71609659-32db3580-2bc5-11ea-978c-f77fa774e969.png)
VlnPlot(testic, 'nucleosome_signal') drawing like below:
![image](https://user-images.githubusercontent.com/41668708/71609823-9023b680-2bc6-11ea-8f7e-1b39acd7e7be.png)

**Comment by timoast** [comment] 2019-12-31 15:30
Thanks. Can you share the object, or a downsampled version, that reproduces this issue so I can look into it further?

**Comment by honghh2018** [comment] 2020-01-01 04:53
Hi Tim, 
     The data object was out of lab sequencing data, which means it unable to share  you this data, I am very sorry to tell you that.

**Comment by timoast** [comment] 2020-01-01 19:30
Since I can't reproduce this and you can't share a reproducible example, and this is an issue with Seurat rather than Signac, I will close the issue.

**Closed by timoast** 2020-01-01 19:30 UTC
