### ISSUE TITLE
LinkPeaks connect peaks to genes located on different chromosomes

### ISSUE THREAD

**Issue by YangLi-Bio** [timoast/signac#866] opened 2021-11-13 05:37 UTC
I have used Signac 1.1.1 to link peaks to nearby genes according to the tutorial of Signac, and there is no running time error. However, when I inspect the predicted peak-gene linkages, I found that peaks are linked to genes located to wrong chromosomes.

I have tried running this code a number of times, and I always got the same result, which is as follows. As known, gene ADGRE5 is located on chr19.

![image](https://user-images.githubusercontent.com/35290254/141607203-657859cb-bc8c-41a9-982c-14571244b9ac.png)

The codes as well as sessionInfo() are presented below. Could you please help solve this issue? Thank you!

```r
x = LinkPeaks(object = x, distance = 500000, 
          min.cells = 10,
          peak.assay = "ATAC", expression.assay = 'SCT', 
          method = "pearson",   
          verbose = T)
```
sessionInfo()

R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /opt/intel/19.0.5/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
 [1] grid      splines   stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] SummarizedExperiment_1.20.0 MatrixGenerics_1.2.1        matrixStats_0.61.0         
 [4] qs_0.25.1.1                 beepr_1.3                   qualV_0.3-4                
 [7] KernSmooth_2.23-17          BSgenome_1.58.0             rtracklayer_1.50.0         
[10] Biostrings_2.58.0           XVector_0.30.0              forcats_0.5.0              
[13] stringr_1.4.0               purrr_0.3.4                 readr_1.3.1                
[16] tidyr_1.1.4                 tibble_3.1.6                tidyverse_1.3.0            
[19] optparse_1.7.1              dplyr_1.0.7                 igraph_1.2.8               
[22] data.table_1.14.2           cicero_1.8.1                Gviz_1.34.1                
[25] monocle_2.18.0              DDRTree_0.1.5               irlba_2.3.3                
[28] VGAM_1.1-5                  ggplot2_3.3.5               Matrix_1.3-4               
[31] SeuratObject_4.0.2          Seurat_4.0.2                Signac_1.1.1               
[34] hash_2.2.6.1                ensembldb_2.14.1            AnnotationFilter_1.14.0    
[37] GenomicFeatures_1.42.3      AnnotationDbi_1.52.0        Biobase_2.50.0             
[40] GenomicRanges_1.42.0        GenomeInfoDb_1.26.7         IRanges_2.24.1             
[43] S4Vectors_0.28.1            BiocGenerics_0.36.1        

loaded via a namespace (and not attached):
  [1] rappdirs_0.3.3           SnowballC_0.7.0          scattermore_0.7          GGally_2.1.2            
  [5] bit64_4.0.5              knitr_1.36               DelayedArray_0.16.3      rpart_4.1-15            
  [9] RCurl_1.98-1.5           generics_0.1.1           cowplot_1.1.1            RSQLite_2.2.8           
 [13] RApiSerialize_0.1.0      RANN_2.6.1               combinat_0.0-8           future_1.23.0           
 [17] bit_4.0.4                lubridate_1.7.9          spatstat.data_2.1-0      xml2_1.3.2              
 [21] httpuv_1.6.3             assertthat_0.2.1         viridis_0.6.2            xfun_0.28               
 [25] hms_1.1.1                promises_1.2.0.1         fansi_0.5.0              progress_1.2.2          
 [29] readxl_1.3.1             dbplyr_2.1.1             DBI_1.1.1                htmlwidgets_1.5.4       
 [33] sparsesvd_0.2            reshape_0.8.8            spatstat.geom_2.3-0      ellipsis_0.3.2          
 [37] backports_1.3.0          RcppParallel_5.0.2       biomaRt_2.46.3           deldir_1.0-6            
 [41] vctrs_0.3.8              ROCR_1.0-11              abind_1.4-5              cachem_1.0.6            
 [45] withr_2.4.2              ggforce_0.3.3            checkmate_2.0.0          sctransform_0.3.2       
 [49] GenomicAlignments_1.26.0 prettyunits_1.1.1        getopt_1.20.3            goftest_1.2-3           
 [53] cluster_2.1.0            lazyeval_0.2.2           crayon_1.4.2             pkgconfig_2.0.3         
 [57] slam_0.1-48              tweenr_1.0.2             nlme_3.1-148             ProtGenerics_1.22.0     
 [61] nnet_7.3-14              rlang_0.4.12             globals_0.14.0           lifecycle_1.0.1         
 [65] miniUI_0.1.1.1           BiocFileCache_1.14.0     modelr_0.1.8             dichromat_2.0-0         
 [69] cellranger_1.1.0         polyclip_1.10-0          lmtest_0.9-39            graph_1.68.0            
 [73] ggseqlogo_0.1            zoo_1.8-9                reprex_0.3.0             base64enc_0.1-3         
 [77] ggridges_0.5.3           pheatmap_1.0.12          stringfish_0.15.4        png_0.1-7               
 [81] viridisLite_0.4.0        bitops_1.0-7             blob_1.2.2               parallelly_1.28.1       
 [85] jpeg_0.1-9               scales_1.1.1             memoise_2.0.0            magrittr_2.0.1          
 [89] plyr_1.8.6               ica_1.0-2                audio_0.1-8              zlibbioc_1.36.0         
 [93] compiler_4.0.2           HSMMSingleCell_1.10.0    RColorBrewer_1.1-2       fitdistrplus_1.1-6      
 [97] Rsamtools_2.6.0          cli_3.1.0                listenv_0.8.0            patchwork_1.1.1         
[101] pbapply_1.5-0            htmlTable_2.3.0          Formula_1.2-4            MASS_7.3-51.6           
[105] mgcv_1.8-31              tidyselect_1.1.1         stringi_1.7.5            densityClust_0.3        
[109] askpass_1.1              latticeExtra_0.6-29      ggrepel_0.9.1            VariantAnnotation_1.36.0
[113] fastmatch_1.1-3          tools_4.0.2              future.apply_1.8.1       rstudioapi_0.13         
[117] foreign_0.8-80           lsa_0.73.2               gridExtra_2.3            farver_2.1.0            
[121] Rtsne_0.15               digest_0.6.28            BiocManager_1.30.16      FNN_1.1.3               
[125] shiny_1.7.1              qlcMatrix_0.9.7          Rcpp_1.0.7               broom_0.7.0             
[129] later_1.3.0              RcppAnnoy_0.0.19         OrganismDbi_1.32.0       httr_1.4.2              
[133] ggbio_1.38.0             biovizBase_1.38.0        colorspace_2.0-2         rvest_0.3.6             
[137] fs_1.5.0                 XML_3.99-0.8             tensor_1.5               reticulate_1.22         
[141] uwot_0.1.10              RBGL_1.66.0              RcppRoll_0.3.0           spatstat.utils_2.2-0    
[145] plotly_4.10.0            xtable_1.8-4             jsonlite_1.7.2           R6_2.5.1                
[149] Hmisc_4.6-0              pillar_1.6.4             htmltools_0.5.2          mime_0.12               
[153] glue_1.5.0               fastmap_1.1.0            BiocParallel_1.24.1      codetools_0.2-16        
[157] utf8_1.2.2               lattice_0.20-41          spatstat.sparse_2.0-0    curl_4.3.2              
[161] leiden_0.3.9             openssl_1.4.5            survival_3.1-12          limma_3.46.0            
[165] docopt_0.7.1             fastICA_1.2-3            munsell_0.5.0            GenomeInfoDbData_1.2.4  
[169] haven_2.3.1              reshape2_1.4.4           gtable_0.3.0             spatstat.core_2.3-1

**Comment by timoast** [comment] 2021-11-13 14:10
Can you show the output of:

```r
annot <- Annotation(x)
x[x$gene_name == "ADGRE5"]
```

**Comment by YangLi-Bio** [comment] 2021-11-13 17:20
Thanks for your information.

This is the output of your two lines of codes.

`GRanges object with 276 ranges and 5 metadata columns:
                  seqnames            ranges strand |           tx_id
                     <Rle>         <IRanges>  <Rle> |     <character>
  ENSE00002791312    chr19 14380501-14380616      + | ENST00000587728
  ENSE00002872200    chr19 14381156-14381545      + | ENST00000358600
  ENSE00002848936    chr19 14381365-14381545      + | ENST00000587535
  ENSE00002908205    chr19 14381416-14381545      + | ENST00000586517
  ENSE00002908205    chr19 14381416-14381545      + | ENST00000587606
              ...      ...               ...    ... .             ...
  ENST00000592261    chr19 14381524-14381545      + | ENST00000592261
  ENST00000592261    chr19 14388450-14388500      + | ENST00000592261
  ENST00000592261    chr19 14388702-14388818      + | ENST00000592261
  ENST00000592261    chr19 14390924-14391079      + | ENST00000592261
  ENST00000592261    chr19 14397077-14397223      + | ENST00000592261
                    gene_name         gene_id   gene_biotype     type
                  <character>     <character>    <character> <factor>
  ENSE00002791312      ADGRE5 ENSG00000123146 protein_coding     exon
  ENSE00002872200      ADGRE5 ENSG00000123146 protein_coding     exon
  ENSE00002848936      ADGRE5 ENSG00000123146 protein_coding     exon
  ENSE00002908205      ADGRE5 ENSG00000123146 protein_coding     exon
  ENSE00002908205      ADGRE5 ENSG00000123146 protein_coding     exon
              ...         ...             ...            ...      ...
  ENST00000592261      ADGRE5 ENSG00000123146 protein_coding      cds
  ENST00000592261      ADGRE5 ENSG00000123146 protein_coding      cds
  ENST00000592261      ADGRE5 ENSG00000123146 protein_coding      cds
  ENST00000592261      ADGRE5 ENSG00000123146 protein_coding      cds
  ENST00000592261      ADGRE5 ENSG00000123146 protein_coding      cds
  -------
  seqinfo: 25 sequences from hg38 genome`

I think the annotation is right.

**Comment by YangLi-Bio** [comment] 2021-11-14 02:21
Hi Tim,

I also tried Signac 1.4.0 on the same data. I think maybe I have found the reason. On line 274 of the R script "links.R", peaks.keep saves the indices among the row names of the ATAC matrix, while the "granges" function on line 296 of this script will re-order the peaks in lexicographic order. Therefore, using "peaks.keep" to index the position in "peaks" is wrong.

We might need fix this issue by substituting the "peaks <- granges(x = object[[peak.assay]])" with "peaks <- StringToGRanges(rownames(object[[peak.assay]]))". Please check it. Thank you!

**Comment by timoast** [comment] 2021-11-15 16:33
> while the "granges" function on line 296 of this script will re-order the peaks in lexicographic order. 

Not sure this is correct...can you share the full code you used to create your object?

**Comment by timoast** [comment] 2021-11-22 16:36
@YangLi-Bio any update on this?

**Comment by YangLi-Bio** [comment] 2021-11-22 16:43
Hi Tim,

I have updated all packages and will try it according to your suggestions today.

If I obtain some results, I will update it today.

Thank you!

**Comment by YangLi-Bio** [comment] 2021-11-23 19:58
I have updated all packages and then test the "LinkPeaks" function. This issue still exists. The full codes are presented below.

`library(Signac)
library(BSgenome.Hsapiens.UCSC.hg38)
library(Seurat)

a <- seurat.ll[[1]] # a list of Seurat objects
DefaultAssay(a) <- "ATAC"
a <- RegionStats(a, genome = BSgenome.Hsapiens.UCSC.hg38)
a <- LinkPeaks(
  object = a,
  peak.assay = "ATAC",
  expression.assay = "SCT",
  genes.use = rownames(a[['SCT']])[1:500]
)

a@assays$ATAC@links
save(a, file = "object.RData")`

The results are presented as follows.

======================================================
       seqnames             ranges strand |     score        gene                   peak    zscore     pvalue
          <Rle>          <IRanges>  <Rle> | <numeric> <character>            <character> <numeric>  <numeric>
   [1]     chr1  14380501-54406763      * |  0.247353      ADGRE5 chr1-54404839-54408687   1.89954 0.02874670
   [2]     chr1 14380501-109616707      * | -0.209147      ADGRE5 chr1-109615570-10961..  -1.97358 0.02421470
   [3]     chr1 14380501-160098197      * | -0.335662      ADGRE5 chr1-160096379-16010..  -2.79391 0.00260372
   [4]     chr1 60087840-202927204      * | -0.247699    MIR646HG chr1-202926505-20292..  -1.85129 0.03206404
   [5]     chr1 73142261-179954679      * |  0.343118      FCHSD2 chr1-179953564-17995..   2.75266 0.00295569
======================================================

As known, the gene "ADGRE5" is located on chr19, however, it has been linked to many peaks located on chr1.

**Comment by timoast** [comment] 2021-11-23 20:16
Can you show the full code used to process the Seurat object before running `LinkPeaks()`?

**Comment by YangLi-Bio** [comment] 2021-11-23 20:42
Hi Tim,

This object was generated by following the analysis pipeline of Seurat (https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html#wnn-analysis-of-10x-multiome-rna-atac-1). It has been preprocessed for a long time. Hence, I only saved this RData file. 

Fur the purpose of debugging, I uploaded this RData to Google Drive (https://drive.google.com/file/d/1uISebRD4qIx9bZQT6pDvTwL_nQRuGxro/view?usp=sharing). Please check this file.

**Comment by timoast** [comment] 2021-11-23 21:05
So the reason you're seeing peaks linked to the wrong genes is that the granges information in your object is not in the same order as the count matrix. However, I don't know how this would have happened, so if you can share the exact code you ran that would be very helpful.

Is it possible you modified the `granges` slot directly at any point? I tried a few things like merging and splitting objects to see if I could reproduce this issue where the granges are in the wrong order but couldn't find anything that would recreate what's in this object.

**Comment by YangLi-Bio** [comment] 2021-11-23 21:11
Hi Tim,

In order to reproduce the result, I tried using the dataset of "Joint RNA and ATAC analysis: 10x multiomic
vignette" (https://satijalab.org/signac/articles/pbmc_multiomic.html), but I always got an error: 

`Error in .order_seqlevels(chrom_sizes[, "chrom"]) : !anyNA(m31) is not TRUE`

 when running the code:

`seqlevelsStyle(annotation) <- "UCSC"
`

Hence, I will have to use the RData saved previously. In addition, I have never revise the codes of any packages.

**Comment by timoast** [comment] 2021-11-23 21:13
That error can be resolved by updating `GenomeInfoDb` (https://github.com/timoast/signac/issues/826)

**Comment by YangLi-Bio** [comment] 2021-11-23 21:15
Thanks. 

I will try it now on the dataset of "Joint RNA and ATAC analysis: 10x multiomic
vignette" (https://satijalab.org/signac/articles/pbmc_multiomic.html) after updating GenomeInfoDb.

**Comment by YangLi-Bio** [comment] 2021-11-24 00:55
Hi Tim,

I have re-installed the package GenomeInfoDb to the up-to-date version, yet this issue still exists. Therefore, I cannot reproduce the analysis in the vignette (https://satijalab.org/signac/articles/pbmc_multiomic.html).

**Comment by timoast** [comment] 2021-11-24 12:56
What's the output of `packageVersion("GenomeInfoDb")`?

If you can provide the exact code you ran to construct this object, that would really help

**Comment by timoast** [comment] 2021-11-29 12:56
@YangLi-Bio any update on this?

**Comment by YangLi-Bio** [comment] 2021-11-30 04:57
> @YangLi-Bio any update on this?

Hi Tim,

The version of GenomeInfoDb is 1.26.7, which is not the latest. However, I cannot install GenomeInfoDb 1.30 even if I tried to re-install it several times.

Could you please tell me how I can install GenomeInfoDb forcefully?

**Comment by YangLi-Bio** [comment] 2021-11-30 05:12
Hi Tim,

I have installed the latest version of GenomeInfoDb. Now I am reproducing the results of Signac vignette (https://satijalab.org/signac/articles/pbmc_multiomic.html). As long as I succeed in reproducing the results, I will make the update here.

**Comment by YangLi-Bio** [comment] 2021-11-30 23:06
Hi Tim,

This issue has been solved. I have reproduced the result in the vignette. The reason is probably the version of GenomInfoDb.

Thank you!

**Closed** 2021-11-30 23:06 UTC
Labels: bug
