### ISSUE TITLE
Not able to set Gene Annotations with EnsDb.Mmusculus.v79

### ISSUE THREAD

**Issue by Chris-Mari** [timoast/signac#867] opened 2021-11-13 17:41 UTC
Dear timoast,
I am getting started with Signac and I am trying to apply the Signac Vignette to a mouse dataset. I am starting from CellRanger outputs using the mouse reference genome available on the 10X genomics website (mm10). This is the code I used:

```
library(Signac)
library(Seurat)
library(GenomeInfoDb)
library(EnsDb.Mmusculus.v79)
library(ggplot2)
library(patchwork)
set.seed(1234)

#Creating Seurat Object
counts <- Read10X_h5(filename = "./filtered_peak_bc_matrix.h5") #Raw counts
metadata <- read.csv("./singlecell.csv", header = T, row.names = 1) #The file singlecell.csv from Cellranger-atac output

chrom_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  genome = "mm10",
  fragments = './fragments.tsv.gz',
  min.cells = 10,
  min.features = 200
)

WT1 <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks",
  project = "WT1",
  meta.data = metadata
)

# extract gene annotations from EnsDb
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79)

# change to UCSC style since the data was mapped to mm10
seqlevelsStyle(annotations) <- 'UCSC'
genome(annotations) <- "mm10"

# add the gene information to the object
Annotation(WT1) <- annotations
```

When I run the last command to add the gene information to the Seurat object I get this error:

```
Error in vapply(X = keyed.objects, FUN = function(x) { : 
  values must be length 1,
 but FUN(X[[1]]) result is length 0

```
Not sure why I am getting this error. I can see that the CreateChromatinAssay function has an annotation argument, so I tried to pass the GRanges from EnsDb.Mmusculus.v79 on that argument.
Another thing I noticed is that chrom_assay@ranges@seqinfo has NAs

```
Seqinfo object with 28 sequences from an unspecified genome; no seqlengths:
  seqnames   seqlengths isCircular genome
  chr1             <NA>       <NA>   <NA>
  chr2             <NA>       <NA>   <NA>
  chr3             <NA>       <NA>   <NA>
  chr4             <NA>       <NA>   <NA>
  chr5             <NA>       <NA>   <NA>
  ...               ...        ...    ...
  GL456221.1       <NA>       <NA>   <NA>
  GL456233.1       <NA>       <NA>   <NA>
  JH584292.1       <NA>       <NA>   <NA>
  JH584295.1       <NA>       <NA>   <NA>
  JH584304.1       <NA>       <NA>   <NA>
```

Am I missing something? I don't have much experience with chromatin assays so any input would be appreaciated.

Thank you so much for your time!
Christian

**Comment by timoast** [comment] 2021-11-13 18:26
Can you show the output of `head(annotations)`?

**Comment by Chris-Mari** [comment] 2021-11-13 18:41
Sure, this is the output:

```
> head(annotations)
GRanges object with 6 ranges and 5 metadata columns:
                     seqnames          ranges strand |              tx_id   gene_name            gene_id
                        <Rle>       <IRanges>  <Rle> |        <character> <character>        <character>
  ENSMUSE00001236884     chr3 3508030-3508332      + | ENSMUST00000108393       Hnf4g ENSMUSG00000017688
  ENSMUSE00000676606     chr3 3634150-3634347      + | ENSMUST00000108394       Hnf4g ENSMUSG00000017688
  ENSMUSE00001345708     chr3 3638059-3638230      + | ENSMUST00000108393       Hnf4g ENSMUSG00000017688
  ENSMUSE00001345708     chr3 3638059-3638230      + | ENSMUST00000108394       Hnf4g ENSMUSG00000017688
  ENSMUSE00000149313     chr3 3641223-3641317      + | ENSMUST00000108393       Hnf4g ENSMUSG00000017688
  ENSMUSE00000149313     chr3 3641223-3641317      + | ENSMUST00000108394       Hnf4g ENSMUSG00000017688
                       gene_biotype     type
                        <character> <factor>
  ENSMUSE00001236884 protein_coding     exon
  ENSMUSE00000676606 protein_coding     exon
  ENSMUSE00001345708 protein_coding     exon
  ENSMUSE00001345708 protein_coding     exon
  ENSMUSE00000149313 protein_coding     exon
  ENSMUSE00000149313 protein_coding     exon
  -------
  seqinfo: 22 sequences from mm10 genome
```

Also this is the output from genome(annotations):

```
> genome(annotations)
  chr3   chrX  chr16   chr7  chr11   chr6  chr13   chr4   chr9   chrY  chr17   chr5   chr2  chr14  chr10   chr8 
"mm10" "mm10" "mm10" "mm10" "mm10" "mm10" "mm10" "mm10" "mm10" "mm10" "mm10" "mm10" "mm10" "mm10" "mm10" "mm10" 
 chr15  chr18   chr1  chr12  chr19   chrM 
"mm10" "mm10" "mm10" "mm10" "mm10" "mm10" 
```

And this is the output from genome(WT1), the Seurat object

```
> genome(WT1)
                chr1                 chr2                 chr3                 chr4                 chr5 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
                chr6                 chr7                 chr8                 chr9                chr10 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
               chr11                chr12                chr13                chr14                chr15 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
               chr16                chr17                chr18                chr19                 chrX 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
                chrY                 chrM    chr1_GL455991_alt    chr1_GL455992_alt    chr1_GL455993_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr1_GL456005_alt    chr1_JH584315_alt    chr1_JH584320_alt    chr1_JH584321_alt    chr1_JH584322_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr2_GL456024_alt    chr3_GL456006_alt    chr3_GL456007_alt    chr3_GL456008_alt    chr3_GL456042_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr3_GL456044_alt    chr3_GL456045_alt    chr3_GL456048_alt    chr3_GL456049_alt    chr3_JH584323_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr4_GL455994_alt    chr4_GL456009_alt    chr4_GL456010_alt    chr4_GL456053_alt    chr4_GL456064_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr4_GL456075_alt    chr4_GL456076_alt    chr4_GL456077_alt    chr4_JH584268_alt    chr4_JH584269_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr4_JH584324_alt    chr4_JH584325_alt    chr4_JH584326_alt    chr5_GL455995_alt    chr5_GL456011_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr6_GL456012_alt    chr6_GL456025_alt    chr6_GL456026_alt    chr6_GL456054_alt    chr6_GL456065_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr6_JH584264_alt    chr7_GL455989_alt    chr7_GL456013_alt    chr7_GL456014_alt    chr8_GL455996_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr8_GL455997_alt   chr10_GL456015_alt   chr11_GL455998_alt   chr11_GL456016_alt   chr11_GL456060_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chr11_JH584265_alt   chr11_JH584316_alt   chr11_JH584317_alt   chr11_JH584327_alt   chr12_GL456017_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chr12_GL456068_alt   chr12_GL456074_alt   chr12_GL456078_alt   chr12_GL456349_alt   chr13_GL455990_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chr13_GL455999_alt   chr13_JH584305_alt   chr14_GL456019_alt   chr14_GL456020_alt   chr15_GL456000_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chr15_JH584270_alt   chr16_GL456001_alt   chr16_GL456028_alt   chr16_JH584306_alt   chr16_JH584307_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chr16_JH584310_alt   chr16_JH584311_alt   chr16_JH584312_alt   chr16_JH584313_alt   chr16_JH584314_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chr17_GL456002_alt   chr17_GL456021_alt   chr17_GL456022_alt   chr17_GL456069_alt   chr17_JH584266_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chr17_JH584267_alt   chr17_JH584308_alt   chr17_JH584309_alt   chr17_JH584328_alt   chr17_JH590470_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chr18_GL456070_alt   chr18_JH584318_alt   chr19_GL456079_alt   chr19_JH584319_alt    chrX_GL456003_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chrX_GL456004_alt    chrX_GL456031_alt    chrX_GL456032_alt    chrX_GL456033_alt    chrY_GL456071_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chrY_GL456072_alt    chrY_GL456073_alt    chrY_GL456080_alt    chrY_GL456081_alt    chrY_GL456082_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chrna_GL456050_alt chr1_GL456210_random chr1_GL456211_random chr1_GL456212_random chr1_GL456213_random 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
chr1_GL456221_random chr4_GL456216_random chr4_GL456350_random chr4_JH584292_random chr4_JH584293_random 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
chr4_JH584294_random chr4_JH584295_random chr5_GL456354_random chr5_JH584296_random chr5_JH584297_random 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
chr5_JH584298_random chr5_JH584299_random chr7_GL456219_random chrX_GL456233_random chrY_JH584300_random 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
chrY_JH584301_random chrY_JH584302_random chrY_JH584303_random       chrUn_GL456239       chrUn_GL456359 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
      chrUn_GL456360       chrUn_GL456366       chrUn_GL456367       chrUn_GL456368       chrUn_GL456370 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
      chrUn_GL456372       chrUn_GL456378       chrUn_GL456379       chrUn_GL456381       chrUn_GL456382 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
      chrUn_GL456383       chrUn_GL456385       chrUn_GL456387       chrUn_GL456389       chrUn_GL456390 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
      chrUn_GL456392       chrUn_GL456393       chrUn_GL456394       chrUn_GL456396       chrUn_JH584304 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr1_KV575232_fix    chr1_KV575233_fix    chr1_KV575234_fix    chr2_KV575235_fix    chr2_KV575236_fix 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr3_KQ030484_fix    chr3_KZ289064_fix    chr3_KZ289065_fix    chr3_KZ289066_fix    chr4_JH792826_fix 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr4_KQ030485_fix    chr4_KQ030486_fix    chr4_KQ030487_fix    chr4_KQ030488_fix    chr4_KQ030489_fix 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr4_KZ289067_fix    chr4_KZ289068_fix    chr4_KZ289069_fix    chr4_KZ289070_fix    chr5_JH792827_fix 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr5_KV575237_fix    chr6_KK082442_fix    chr6_KK082443_fix    chr7_JH792828_fix    chr7_KV575238_fix 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr7_KV575239_fix    chr8_KV575240_fix    chr9_KB469738_fix    chr9_KQ030490_fix   chr10_KQ030491_fix 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chr10_KZ289071_fix   chr10_KZ289072_fix   chr11_KB469739_fix   chr11_KZ289076_fix   chr12_KB469740_fix 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chr12_KZ289082_fix   chr14_KZ289083_fix   chr14_KZ289084_fix   chr15_KQ030492_fix   chr15_KQ030493_fix 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chr15_KV575241_fix   chr15_KZ289085_fix   chr15_KZ289086_fix   chr16_KB469741_fix   chr17_KB469742_fix 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chr17_KZ289087_fix   chr17_KZ289088_fix   chr17_KZ289089_fix   chr18_JH792829_fix   chr18_KZ289090_fix 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chr18_KZ289091_fix   chr19_JH792830_fix   chr19_KQ030494_fix   chr19_KV575242_fix    chrX_JH792831_fix 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chrX_KQ030495_fix    chrX_KQ030496_fix    chrX_KQ030497_fix    chrX_KZ289092_fix    chrX_KZ289093_fix 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chrX_KZ289094_fix    chrX_KZ289095_fix    chrY_JH792832_fix    chrY_JH792833_fix    chrY_JH792834_fix 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
   chr1_KK082441_alt   chr11_KZ289073_alt   chr11_KZ289074_alt   chr11_KZ289075_alt   chr11_KZ289077_alt 
              "mm10"               "mm10"               "mm10"               "mm10"               "mm10" 
  chr11_KZ289078_alt   chr11_KZ289079_alt   chr11_KZ289080_alt   chr11_KZ289081_alt 
              "mm10"               "mm10"               "mm10"               "mm10" 
```

**Comment by timoast** [comment] 2021-11-13 19:39
I'm not able to reproduce this issue, can you try restarting R (making sure the environment is not saved in RStudio), and re-running this?

**Comment by Chris-Mari** [comment] 2021-11-13 20:14
I tried to restart R and RStudio without saving anything, when I rerun the code I still get the same error when I try to add the annotations.

This data is from a publicly available dataset https://www.ncbi.nlm.nih.gov/sra?term=SRX7170302 so I downloaded the fastq files from SRA and then run the cellranger-atac pipeline. It completed without any errors so I think the original data is ok. The web_summary.html file from CellRanger looks fine, including the TSS enrichment that looks similar to the TSSenrichment function in Signac.
[web_summary.html.zip](https://github.com/timoast/signac/files/7532679/web_summary.html.zip)

**Comment by Chris-Mari** [comment] 2021-11-13 20:37
Update:
Interestingly, I get the same exact error if I use the brain test dataset described in the Signac vignette, which seems to exclude issues with the other dataset. Seems an issue with R on my machine. Could it be an issue with R packages?

Not sure if it helps but this is my session Info:

```
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] stringr_1.4.0              patchwork_1.1.1            ggplot2_3.3.5             
 [4] EnsDb.Mmusculus.v79_2.99.0 ensembldb_2.16.4           AnnotationFilter_1.16.0   
 [7] GenomicFeatures_1.44.2     AnnotationDbi_1.54.1       Biobase_2.52.0            
[10] GenomicRanges_1.44.0       GenomeInfoDb_1.30.0        IRanges_2.26.0            
[13] S4Vectors_0.30.2           BiocGenerics_0.38.0        SeuratObject_4.0.3        
[16] Seurat_4.0.5               Signac_1.4.0              

loaded via a namespace (and not attached):
  [1] utf8_1.2.2                  reticulate_1.22             tidyselect_1.1.1           
  [4] RSQLite_2.2.8               htmlwidgets_1.5.4           grid_4.1.1                 
  [7] docopt_0.7.1                BiocParallel_1.26.2         Rtsne_0.15                 
 [10] munsell_0.5.0               codetools_0.2-18            ica_1.0-2                  
 [13] future_1.23.0               miniUI_0.1.1.1              withr_2.4.2                
 [16] colorspace_2.0-2            filelock_1.0.2              knitr_1.36                 
 [19] rstudioapi_0.13             ROCR_1.0-11                 tensor_1.5                 
 [22] listenv_0.8.0               MatrixGenerics_1.4.3        slam_0.1-48                
 [25] GenomeInfoDbData_1.2.6      polyclip_1.10-0             bit64_4.0.5                
 [28] farver_2.1.0                parallelly_1.28.1           vctrs_0.3.8                
 [31] generics_0.1.1              xfun_0.28                   biovizBase_1.40.0          
 [34] BiocFileCache_2.0.0         lsa_0.73.2                  ggseqlogo_0.1              
 [37] R6_2.5.1                    hdf5r_1.3.4                 bitops_1.0-7               
 [40] spatstat.utils_2.2-0        cachem_1.0.6                DelayedArray_0.18.0        
 [43] assertthat_0.2.1            promises_1.2.0.1            BiocIO_1.2.0               
 [46] scales_1.1.1                nnet_7.3-16                 gtable_0.3.0               
 [49] globals_0.14.0              goftest_1.2-3               rlang_0.4.12               
 [52] RcppRoll_0.3.0              splines_4.1.1               rtracklayer_1.52.1         
 [55] lazyeval_0.2.2              dichromat_2.0-0             checkmate_2.0.0            
 [58] spatstat.geom_2.3-0         yaml_2.2.1                  reshape2_1.4.4             
 [61] abind_1.4-5                 backports_1.3.0             httpuv_1.6.3               
 [64] Hmisc_4.6-0                 tools_4.1.1                 ellipsis_0.3.2             
 [67] spatstat.core_2.3-1         RColorBrewer_1.1-2          ggridges_0.5.3             
 [70] Rcpp_1.0.7                  plyr_1.8.6                  base64enc_0.1-3            
 [73] progress_1.2.2              zlibbioc_1.38.0             purrr_0.3.4                
 [76] RCurl_1.98-1.5              prettyunits_1.1.1           rpart_4.1-15               
 [79] deldir_1.0-6                pbapply_1.5-0               cowplot_1.1.1              
 [82] zoo_1.8-9                   SummarizedExperiment_1.22.0 ggrepel_0.9.1              
 [85] cluster_2.1.2               magrittr_2.0.1              data.table_1.14.2          
 [88] scattermore_0.7             lmtest_0.9-39               RANN_2.6.1                 
 [91] SnowballC_0.7.0             ProtGenerics_1.24.0         fitdistrplus_1.1-6         
 [94] matrixStats_0.61.0          hms_1.1.1                   mime_0.12                  
 [97] xtable_1.8-4                XML_3.99-0.8                jpeg_0.1-9                 
[100] sparsesvd_0.2               gridExtra_2.3               compiler_4.1.1             
[103] biomaRt_2.48.3              tibble_3.1.6                KernSmooth_2.23-20         
[106] crayon_1.4.2                htmltools_0.5.2             mgcv_1.8-38                
[109] later_1.3.0                 Formula_1.2-4               tidyr_1.1.4                
[112] DBI_1.1.1                   tweenr_1.0.2                dbplyr_2.1.1               
[115] MASS_7.3-54                 rappdirs_0.3.3              Matrix_1.3-4               
[118] igraph_1.2.8                pkgconfig_2.0.3             GenomicAlignments_1.28.0   
[121] foreign_0.8-81              plotly_4.10.0               spatstat.sparse_2.0-0      
[124] xml2_1.3.2                  XVector_0.32.0              VariantAnnotation_1.38.0   
[127] digest_0.6.28               sctransform_0.3.2           RcppAnnoy_0.0.19           
[130] spatstat.data_2.1-0         Biostrings_2.60.2           leiden_0.3.9               
[133] fastmatch_1.1-3             htmlTable_2.3.0             uwot_0.1.10                
[136] restfulr_0.0.13             curl_4.3.2                  shiny_1.7.1                
[139] Rsamtools_2.8.0             rjson_0.2.20                lifecycle_1.0.1            
[142] nlme_3.1-153                jsonlite_1.7.2              BSgenome_1.60.0            
[145] viridisLite_0.4.0           fansi_0.5.0                 pillar_1.6.4               
[148] lattice_0.20-45             KEGGREST_1.32.0             fastmap_1.1.0              
[151] httr_1.4.2                  survival_3.2-13             glue_1.5.0                 
[154] qlcMatrix_0.9.7             png_0.1-7                   bit_4.0.4                  
[157] ggforce_0.3.3               stringi_1.7.5               blob_1.2.2                 
[160] latticeExtra_0.6-29         memoise_2.0.0               dplyr_1.0.7                
[163] irlba_2.3.3                 future.apply_1.8.1 


```

**Comment by timoast** [comment] 2021-11-15 16:51
Yeah this seems like some issue with your R installation. I'm not sure what the issue is exactly, but I'd suggest reinstalling Signac and its dependencies, and if that doesn't work maybe try reinstalling R itself. I'll close this issue since I don't think this is caused by any bug in Signac itself

**Closed by timoast** 2021-11-15 16:51 UTC

**Comment by Chris-Mari** [comment] 2021-11-15 17:07
I tried to do a complete clean install of R, by removing also the folder containing packages after uninstalling R. Then I reinstalled the latest version of R and R studio, Signac and all its dependencies, but unexpectedly I still get the same error on the annotations step.

Interestingly, if I add the annotations on on the chrom_assay object with `Annotation(chrom_assay) <- annotations` I don't get the error. But then the I get the error when I try to do the QC steps

```
> WT1 <- TSSEnrichment(WT1, fast = FALSE)
Extracting TSS positions
Finding + strand cut sites
[W::hts_idx_load2] The index file is older than the data file: /Users/christian/Desktop/scRNAseq/Datasets/scATAC-seq/TestBrain/atac_v1_adult_brain_fresh_5k_fragments.tsv.gz.tbi
Finding - strand cut sites
[W::hts_idx_load2] The index file is older than the data file: /Users/christian/Desktop/scRNAseq/Datasets/scATAC-seq/TestBrain/atac_v1_adult_brain_fresh_5k_fragments.tsv.gz.tbi
Computing mean insertion frequency in flanking regions
Normalizing TSS score
Error in vapply(X = keyed.objects, FUN = function(x) { : 
  values must be length 1,
 but FUN(X[[1]]) result is length 0
```

That's unfortunate I am not able to use Signac, but I am out of ideas and can't understand why I get this error.

**Comment by timoast** [comment] 2021-11-15 17:13
I unfortunately don't know why this would be happening, and since I can't reproduce the issue on my end there's not much I can do to look into it further. We do provide docker images for Signac that you could use instead: https://satijalab.org/signac/articles/install.html#docker

**Comment by Chris-Mari** [comment] 2021-11-15 21:16
Hi timoast,
I was able to solve the problem I'll just comment here for future reference. The issue is related to the latest version of the SeuratObject package, version 4.0.3
I downgraded the package to version 4.0.2 and the error is gone when I add the annotations through the Annotation function. Not sure what triggers the error in version 4.0.3
Glad I can use Signac now!

**Comment by mdozmorov** [comment] 2021-11-25 00:14
Ran into exactly the same problem, and the solution by @Chris-Mari worked. The command to downgrade:
``` r
devtools::install_version("SeuratObject", version = "4.0.2", repos = "http://cran.us.r-project.org")
```
