### ISSUE TITLE
CreateChromatinAssay Bug--Number of ranges provided is not equal to the number  of features in the assay

### ISSUE THREAD

**Issue by gbloeb** [timoast/signac#191] opened 2020-08-13 21:38 UTC
If min.cells set to >0, some features will be eliminated and then number of ranges (supplied or derived) will be different than number of ranges.

This problem can be avoided in meantime by  following:

```
rowcounts<-rowSums(counts)
counts<-counts[rowcounts>5,]. #To eliminate features with less than 5 counts
```

and then setting min.cells=0 in the CreateChromatinAssay function.

**Comment by timoast** [comment] 2020-08-13 21:43
Can you provide a reproducible example? This works for me:

```r
library(Signac)

counts <- GetAssayData(atac_small)
obj <- CreateChromatinAssay(counts = counts, min.cells = 20)
```

**Comment by gbloeb** [comment] 2020-08-18 19:22
Sure.  How should I send it to you?

**Comment by timoast** [comment] 2020-08-18 19:28
You can post the code here if you can reproduce the error with a small public dataset, such as `atac_small`. If you can only reproduce the error with your own dataset, please send a link to the saved object and code to tstuart@nygenome.org

**Comment by timoast** [comment] 2020-08-20 13:42
This should be fixed now on the develop branch. You can install from github using devtools:

```r
if (!requireNamespace("devtools", quietly = TRUE))
    install.packages("devtools")
devtools::install_github("timoast/signac", ref = "develop")
```

**Closed by timoast** 2020-08-20 13:42 UTC
Labels: bug
