### ISSUE TITLE
error while making gene matrix

### ISSUE THREAD

**Issue by hjack123** [timoast/signac#76] opened 2020-01-21 18:35 UTC
Hi Tim
would you have some guidance solving the following error...much appreciated!  (I combined the fragment file and add a letter on barcode which Im not sure if its relevant...)
fragment.path = '../fragments.tsv.gz'
> gene.activities <- FeatureMatrix(
+   fragments = fragment.path,
+   features = genebodyandpromoter.coords,
+   cells = colnames(integrated),
+   chunk = 10
+ )
Extracting reads overlapping genomic regions
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=38m 33s
Constructing matrix
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class "numeric" is not valid for @'Dim' in an object of class "dgTMatrix"; is(value, "integer") is not TRUE

**Comment by timoast** [comment] 2020-01-21 19:13
Can you share a small subset of the fragment file that reproduces the issue?

**Comment by hjack123** [comment] 2020-01-21 19:24
Sure I will. Could it also be the cell barcode else where (colnames(obj)) dont match to the ones in fragment file?

**Comment by timoast** [comment] 2020-01-21 20:12
The cell names will need to match the barcodes in the fragment file, but with no matches the expected behaviour should be to return an empty matrix in this case. You can email the file or a dropbox/google drive link to the file to tstuart@nygenome.org

**Comment by hjack123** [comment] 2020-01-21 22:22
thank you very much for your reply. the file was sent. after I tried to match the barcodes. I got different msg:
Extracting reads overlapping genomic regions
Constructing matrix
Error: Cannot add a different number of cells than already present
Execution halted

The overall goal of mine is just to combine 2 datasets done at the same time (treatment and control) from 10x.
so I did colnames(mtx) <- gsub("^","J_",colnames(mtx)) 
and rownames(metadata)<- gsub("^","J_",rownames(metadata))
before create seurat object.
and did integration...
so welcome to better ways to combine and make gene matrix.... thanks again..!

**Comment by hjack123** [comment] 2020-01-21 23:45
> ##### Integration 2 datasets
> # find union peak set
> peaks1=StringToGRanges(regions=rownames(pbmc.B))
> peaks2=StringToGRanges(regions=rownames(pbmc.J))
> all.peaks <- union(peaks1,peaks2)
> newcounts1 <- FeatureMatrix(fragments = GetFragments(pbmc.B), features = all.peaks)
Extracting reads overlapping genomic regions
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=16m 58s
Constructing matrix
> newcounts2 <- FeatureMatrix(fragments = GetFragments(pbmc.J), features = all.peaks)
Extracting reads overlapping genomic regions
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=21m 38s
Constructing matrix
> pbmc.B[['peakunion']] = CreateAssayObject(counts=newcounts1)
Error: Cannot add a different number of cells than already present

**Comment by hjack123** [comment] 2020-01-22 00:36
for some reason this function
FeatureMatrix
created a count matrix that has different (much larger) number of cells than original barcodes saved in the object...

**Comment by timoast** [comment] 2020-01-22 02:08
Does the small file you sent reproduce the first error for you? It works fine for me.

By default all the cells that are found in the fragment file are included in the output, so you will have cells in the matrix that are not in the object, which is why you get an error when trying to add the assay containing a different number of cells. You first need to subset the matrix or use the `cells` parameter in `FeatureMatrix`.

**Comment by hjack123** [comment] 2020-01-22 19:46
Hi Tim thanks so much for your reply. 
so I changed the cell parameter but later on run into this error under FindIntegrationAnchors

Constructing matrix
Extracting reads overlapping genomic regions
Constructing matrix
Performing TF-IDF normalization
Performing TF-IDF normalization
Scaling features for provided objects
Error in as.vector(x) : no method for coercing this S4 class to a vector
Calls: FindIntegrationAnchors ... ScaleData.default -> as.vector -> intersect -> unique -> as.vector
Execution halted

**Comment by hjack123** [comment] 2020-01-22 19:47
my command:
anchors <- FindIntegrationAnchors(
  object.list = list(pbmc.J, pbmc.B),
  anchor.features = peaks.use,
  assay = c('peakunion', 'peakunion'),
  k.filter = NA
)

**Comment by timoast** [comment] 2020-01-23 14:26
> so I changed the cell parameter but later on run into this error under FindIntegrationAnchors

Since that's a different problem, can you open a new issue and include the full code?

Regarding the original issue, is this fixed now? I couldn't reproduce so I assume it was just to do with the cell names.

**Comment by hjack123** [comment] 2020-01-23 18:07
Thanks I opened the new issue. 
This issue was resolved by adding 'cell' parameter

**Closed** 2020-01-23 18:07 UTC
